### ISSUE TITLE
Admin - Forms - Hide Signature Count field in Submitted Inspections Table

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#1]
Since no inspections get a signature, we should remove field "Signature Count"

![image](https://user-images.githubusercontent.com/4103847/30659612-51784bb6-9e0c-11e7-9032-fdcec06f97f4.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
tested, this is removed, no issue
