### ISSUE TITLE
2 Seeding Type fields in the Seedings Form in Vegetative Review

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#10]
There are 2 Seeding Type fields in the Seedings form.  One is a drop down box to make a selection and then it populates the Seeding Type text box field with the same value. Is this accurate? 

In the example below, the first Seeding type field is a text box and the second Seeding Type field is a drop down box. I selected PGS-WG in the drop down box, and this value was automatically placed in the first Seeding Type field (the text box).

Steps to get to this form
Inspections- Projects - Selected a Vegetative Review Form I created - Seeding - New

![seeding issue](https://user-images.githubusercontent.com/16418393/32061124-c900aac2-ba3e-11e7-9979-9435c0da8aa1.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
This issue is resolved
