### ISSUE TITLE
The drop downs in the New Inspection Form do not work for all options except "Inspection Type". 

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#100]
The drop downs in the New Inspection Form do not work for all options except "Inspection Type". When I attempt to select the drop down box, nothing happed and I get a red exclamation mark as well. I tested on the desktop too incase the ipad was the problem. Same issue. 

To clarify further:
The fields "Meet Project Supervisor" and "PreCon Meeting Attended" should only be able to be selected for the first IRF inspection added to the project. 

Here is a screenshot for example:
![not working](https://user-images.githubusercontent.com/16418393/35284554-09e69dda-0053-11e8-9e02-47d55b48d3a3.JPG)

**Comment by kanglu666** [comment]
fixed, ready for testing

**Comment by leeensminger** [comment]
@kanglu666 @impittman I'm sorry, I just now saw this.  The "Meet Project Supervisor" field should be displayed for all IRF forms.  "PreCon meeting attended" is the only field that should be displayed for the first inspection on the project only, then not again on that project.


And again - if Meet Project Supervisor = No, then the system should display a comments box (required before save), where they can enter a reason why they did not talk to the Project Supervisor.

**Comment by impittman** [comment]
The drops down work. However, the following logic does not work:

If Meet Project Supervisor = No, then the system should display a comments box (required before save), where they can enter a reason why they did not talk to the Project Supervisor.

There is no comment box to type a comment for this logic.

Also, the Precon Meeting attended should only be active for the first inspection of a project per Lee's comments from the stakeholder/requirements. It is currently active for all inspections, not just the first inspection for a new project.

**Comment by ehsan67** [comment]
@leeensminger @impittman 
_" If Meet Project Supervisor = No, then the system should display a comments box (required before save), where they can enter a reason why they did not talk to the Project Supervisor."_
Should I use PM_COMMENT field to save that comment? Or is it going to be a new filed in the database?

**Comment by impittman** [comment]
@ehsan67 @leeensminger 
From my understanding, the PM_COMMENT field is for the comments made under Admin-Forms (screenshot below). I have only seen the "Meet with Supervisor Yes/No" field in the database when QC'ing, though I may have overlooked it. I am pretty sure this will have to be a new field in the database.

PM COMMENTS field appears to relate to this as a heads up:
![pm1](https://user-images.githubusercontent.com/16418393/38566236-c141b51c-3cd2-11e8-80d8-8380e2738b1f.png)

**Comment by ehsan67** [comment]
@impittman @leeensminger  if we add a new field, where do we show it in the UI?

**Comment by leeensminger** [comment]
[ProjectSupervisor.pdf](https://github.com/kcigeospatial/DelDOT-ES2M/files/1895651/ProjectSupervisor.pdf)
@ehsan67 Like this.  In the inspection form, and should be presented dynamically, so that it is only visible and required when Meet Project Supervisor = No.

**Comment by leeensminger** [comment]
@ehsan67 Add new field INSPECTION_RATING_FORM.MEET_SUPERVISOR_REASON

Type = Text, length = 500, not required / nullable

**Comment by leeensminger** [comment]
[New inspection questions.pdf](https://github.com/kcigeospatial/DelDOT-ES2M/files/1900065/New.inspection.questions.pdf)
@ehsan67 @impittman Attached is the logic that is supposed to be in place for new inspections.  Ehsan - please review, and ensure that the application functions in this way. 

This is also mostly captured in the wireframes: M:\2014\17141728.A\Reports\ES2M\Design\Wireframes

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
Meet with the Project Supervisor = No, A text box appeared and I was able to add my reason why. Works well. 

Precon Meeting Attended only appeared on first inspection entered as inspected.

Closing issue.
