### ISSUE TITLE
Could not delete notes with associated photos in the IRF

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#102]
I received the message below when trying to delete a note with an associated photo. The notes without a photo deleted with no problem.

![deleting notes in irf error message](https://user-images.githubusercontent.com/16418393/35295500-39dafcd4-0071-11e8-9d77-836d52c4ca3c.JPG)

**Comment by kanglu666** [comment]
need to delete the assoiated note photo first. 
updated, ready for testing in next release

**Comment by impittman** [comment]
this process works in testing and will be added to the training guide, I think it is ok to close issue
