### ISSUE TITLE
Cannot download BMP Checklist from Admin-Config

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#103]
When selecting a BMP and clicking the download button to download the checklist, I get a 404 server error.

![404](https://user-images.githubusercontent.com/16418393/35296467-06862554-0074-11e8-91cd-ff7ab9c893dd.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this is working without error in testing, can close out
