### ISSUE TITLE
Not getting emails after submitting the inspection

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#104]
We did not get emails once an inspection was submitted. I closed an IRF under this project:
![no_email](https://user-images.githubusercontent.com/16418393/35298816-32354818-007b-11e8-8e9b-15d828c53f55.JPG)

**Comment by kanglu666** [comment]
email function has been added after inspection submitted. ready for testing in next release

**Comment by leeensminger** [comment]
@impittman Closing this since you indicated that the email part works.  New issue to be created for adding the report.
