### ISSUE TITLE
Admin - Project - Project Details - Rename "Date Fields" label

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#105]
Please rename this to "Project Dates"

![image](https://user-images.githubusercontent.com/4103847/35401245-f8b83922-01c6-11e8-8b55-f53679cfcee1.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated, closing issue
