### ISSUE TITLE
Admin - Submitted Inspection Forms - PM Comment does not save

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#107]
The PM Comment does not appear to save.  Is this being impacted by a rule of some kind?

To reproduce:
1. I'm logged in as admin@kci.com
2. Search and find a submitted inspection.  I reproduced this on several submitted inspections.
3. Click Edit Comment at the PM Comment component.  Type a comment in the box.
4. Click Save.  
5. Select a different inspection in the grid.  The PM Comment should update to match the selected inspection, and it does.
6. Select the previous inspection.  The comment that was entered is no longer present.

The screenshot below is after performing the steps above.  When I select the same inspection form, I expect to see the PM Comment, but the text area is empty.

![image](https://user-images.githubusercontent.com/4103847/35401980-2434160a-01c9-11e8-9669-6a60b6e60fef.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
This appears to be working now, I think it is ok to close the issue out.
