### ISSUE TITLE
Inspections - Specifications List - add filter group category "All"

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#108]
In the inspection Specifications, the user can select a spec category to filter the specifications displayed.  This works well.  But when the user selects a spec group, they cannot go back to the default view of "all specs".  Please add a category in the dropdown for "All", that displays all specs.

![image](https://user-images.githubusercontent.com/4103847/35434063-bf57ef46-0253-11e8-8607-04baa7229748.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
a load all button has been added and it works as needed, closing
