### ISSUE TITLE
Inspections - weather

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#109]
What is the rainfall amount that currently defines a "rain event"?

**Comment by leeensminger** [comment]
Per Mary 20180125, should be 0.5"

**Comment by impittman** [comment]
@leeensminger Is the only inspection type that the rainfall event is needed -"Small Construction Diary Form"? Just confirming as this is only inspection type I see the option to enter rainfall event and amount in.

**Comment by leeensminger** [comment]
@impittman that I think is the only place where rainfall is manually entered, yes.  But all other forms should be collecting weather data including precipitation amounts.  The Admin/Submitted Inspection Forms page has functionality to search inspection forms by rain event, which displays only those inspections where there was a rain event.  I am not sure what the current definition of "rain event" is in the app, but per Mary yesterday, it needs to be 0.5".

**Comment by impittman** [comment]
@leeensminger  ok good to know on the forms for entry, I didn't want to miss an update on those in case needed. My other question would be for the "Admin/Submitted Inspection Forms page has functionality" piece - I kind of just looked at this for my understanding in testing and noticed the following:

When I filtered for rain event, I got the two below in the screen shot logged in as admin:
![rain event](https://user-images.githubusercontent.com/16418393/35450854-3205565e-02b9-11e8-8666-8b672c380d55.JPG)

If I understand the requirement, the 0.5 inches should be the day of the inspection correct? Not within 7 days? If this is correct, I don't think the following should be a rain even, yet filtered as such as the rain amount was 0 on the day of the inspection (not submitted date).

This is the weather for the date of inspection for the inspection submitted 1/23 in screen shot above. The precipitation is 0.
![rain amount](https://user-images.githubusercontent.com/16418393/35451009-c21e6fdc-02b9-11e8-826c-1972dcd7c175.JPG)

However, in the 7 day span, it had rain for this inspection, just not the day of. 
 7 day for inspection 
![7 day](https://user-images.githubusercontent.com/16418393/35451233-76d49d66-02ba-11e8-8161-964bfdfd238b.JPG)

**Comment by leeensminger** [comment]
@impittman @ehsan67  Filtering by a rain event should find inspections where a rain event occurred on the inspection day.  Rain event = 0.5" or more.  Filtering by a rain event should not find inspections where a rain event occurred within 7 days, but on the day of the inspection.

**Comment by ehsan67** [comment]
@leeensminger @impittman can you give me the steps and the result that is correct?

**Comment by leeensminger** [comment]
per discussion with Ehsan on the phone:
1) The "query by rain events" functionality does not appear to be working.
2) Confirm that the flag for rain events is >= 0.5"

These might be related.  Also @ehsan67  it appears Lu added a field INSPECTION_RATING_FORM.RAIN_EVENTS to capture this information as a y/n.  So, that says that he's capturing the precipitation amount during the submittal process.  This is where you should confirm the 0.5".

**Comment by ehsan67** [comment]
@leeensminger @impittman  the rain event logic is changed from 0.1 to 0.5. For the existing data the RainEvent flag could be wrong because of the wrong previous number.
ready KCI

**Comment by impittman** [comment]
@ehsan67 I found some issues on the query for rain events when testing today. It appears that inspections with "0" inches of precipitation are still appearing in the query. In addition, 2 inspections with precipitation amount greater than ".5" are missing from the query. See below for details:

Queried on “Rain Events” and Received 6 Inspection Records. Based on the logic for Precipitation Amount, the query should bring back Inspections with at least “0.5 inches” or greater on the Day of Inspection.
**Here is the Query Results:**
![rain event query](https://user-images.githubusercontent.com/16418393/38931349-68ca8d42-4302-11e8-9303-945ff3a07c09.png)

**When confirming the accuracy of the Rain Events query, I found the following:**
-	The Inspection Rating Form with a submitted date of Jan 23rd had a Precipitation Amount of “0” on the date of the Inspection (11/29/2017) based on the Weather data in ES2M (the weather button) and should not have been included in the query (see below as an example for the remaining items):
![jane 23](https://user-images.githubusercontent.com/16418393/38931380-80304a9e-4302-11e8-8213-a56ae1f982a5.png)

-	Inspection Rating Forms  in the list above dated as submitted on Jan 29th, had a Precipitation Amount of “0” on the date of the Inspection based on the Weather data in ES2M and should not have been included in the query.

-	The Inspection Rating Form with a submitted date of Jan 31st  had a Precipitation Amount of “0” on the date of the Inspection (1/3/2018) based on the Weather data in ES2M and should not have been included in the query.


-	The Construction Diary Form with a submitted date of Mar 22nd had a Precipitation Amount of “0” on the date of the Inspection (2/21/2018) based on the Weather data in ES2M and should not have been included in the query.

**I would also expect to see the following in the Query based on precipitation. However, they were not in the query results depicted above**:
-	Vegetative Review Form submitted on Mar 29th had 0.59 inches of Precipitation according to the Weather Data in ES2M (inspection date was 8/15/2017).
![veg review mar 29](https://user-images.githubusercontent.com/16418393/38931537-0bd6e72e-4303-11e8-821a-52159b74609e.png)


-	Inspection Rating Form submitted on Apr 18th had 0.81 inches of Precipitation according to the Weather Data in ES2M (inspection date was 2/7/2018).

**Comment by ehsan67** [comment]
@impittman  did you test on the data that was added before I change the logic from 0.1 to 0.5 in code?

**Comment by impittman** [comment]
@ehsan67 I will create another inspection to confirm today as it is raining. I can check it on 4/20 to ensure all is good. That way we know there was rain and it was past the change date.

**Comment by impittman** [comment]
@leeensminger 
For inspections that have no weather populated from the DEOS weather service, see #144, the rain even function is likely not going to work correctly. For example, inspections were completed on 5/17 where there was definitely rain occurring in high amounts (0.72 in min for inspection county). However, the weather page did not appear to register data and this submitted inspection is not in the Admin- Forms- Rain Event filter as there is no data to support it due to the weather service page not providing data. 

Is this going to be an issue? Do we need a disclaimer in that filter or is this just something to pass along to the user? If a non-issue, this can be closed in GitHub.

**Comment by leeensminger** [comment]
@impittman Have you seen the service? How are you able to verify that there is no data in the DEOS weather service source?

**Comment by impittman** [comment]
@leeensminger I have only verified the message works, some of the weather stations are somewhat of a guess as to if it is the best one to use for proximity. I did notice on DEOS that many stations indeed do have n/a for data we are capturing. Perhaps there is a better service to use?

**Comment by leeensminger** [comment]
"I did notice on DEOS that many stations indeed do have n/a for data we are capturing." 

-- How did you verify that?

**Comment by impittman** [comment]
This site will summarize based on station location:
http://www.deos.udel.edu/data/monthly_retrieval.php

**Comment by impittman** [comment]
@leeensminger to clarify "many of these stations" are either in other neighboring states, but closest to Delaware for getting weather observations, or stations that have data that is spotty in reporting. Also, there are a couple in the middle of the state that had a few months were data was sporadic. The ones closest to the existing inspections I believe are mostly complete, with the exception of a few times in the winter months, or when it may have not recorded for other reasons. See Blackbird Station, Claymont, Glasgow, for the inspections we are currently using. These seem close to sites and are full with data. 
I am not sure how the station location is selected. There are a few that are in close similar proximity to a site, and the station reporting may or may not be fully populated depending on station used. I just went with closest to get these 3 to start and are full of data, mostly.

**Comment by impittman** [comment]
This was resolved with an "No data available message" #144 closing this issue.
