### ISSUE TITLE
Photo Number is missing on the Sample Locations Form in Vegetative Review

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#11]
According to the requirements, a field for the "Photo Number" should be visible on the Sample Locations Form in the Vegetative Review. This attribute is not on the form. 

Steps taken to test:
Inspections - Projects - Select Project - Select a Vegetative Review created - Select Sampled Location - New- enter data - Add photo - Save.

![photo issue](https://user-images.githubusercontent.com/16418393/32061478-ba944826-ba3f-11e7-9ab3-ac2bf8c72fe9.png)

The Requirements for Reference
![requirements 23 0](https://user-images.githubusercontent.com/16418393/32061528-de1cc6b0-ba3f-11e7-8612-34e089ecf452.png)

**Comment by kanglu666** [comment]
sample location itself does not carry Photo Num field.
it has photo table attached, that carries the Photo Num filed.. 
and you can see the photo num in the photo page.

**Comment by impittman** [comment]
this can be closed, non issue after more discussions
