### ISSUE TITLE
Inspections - Weather - Convert to Standard units

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#110]
The weather precipitation and windspeed are currently in metric units.  Please convert to standard units (rainfall = inches, and windspeed = miles per hour (mph)).

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
I think the windspeed is still not recording in MPH from the weather station. I looked at one inspection and compared the windspeed in ES2M to a weather station nearby the inspection site. Please see the differences below:
Inspection Weather Recorded in ES2M
![weather1](https://user-images.githubusercontent.com/16418393/38501271-18db202e-3bfc-11e8-91af-fff6b9b933a6.png)

Note the Temperature and Precipitation closely match the weather station output below:
![precip_temp](https://user-images.githubusercontent.com/16418393/38501315-35146dfe-3bfc-11e8-93ed-4b8ddb7ee558.png)

However, the windspeed in ES2M is no where near the average windspeed. This is true in 10 other ES2M recordings I reviewed against a local weather station as well.
![wind](https://user-images.githubusercontent.com/16418393/38501364-57b372a6-3bfc-11e8-886c-8d38880a684e.png)

**Comment by ehsan67** [comment]
@impittman  there was an issue in calculating the average Wind Speed, however, the conversion to MPH was already in place
ready in KCI

**Comment by impittman** [comment]
this is working as expected during testing, closing issue
