### ISSUE TITLE
Inspections - General - Time In/Out make required for all inspections

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#112]
Per new discussion with Mary 20180125, the time in and out should be required information for all inspections.

This should be enforced at time of submittal - we cannot require users to populate this when they open General Info.

**Comment by kanglu666** [comment]
Time In/Out fields are only in IRF form, not in Construction diary form or  vegetative review form

**Comment by leeensminger** [comment]
Just IRF form

**Comment by ehsan67** [comment]
ready in KCI

**Comment by impittman** [comment]
@ehsan67 I was still able to save the general info form for the IRF without entering the required time out field. Can you confirm that the time in/time out requirement is supposed to be enforced here?
I went to the project beginning with BR3 and created a new inspection rating form for testing (results below).
![timeout](https://user-images.githubusercontent.com/16418393/38674315-9c3c3bf8-3e43-11e8-8a69-b8e136f7aa8d.png)

**Comment by ehsan67** [comment]
@impittman @leeensminger  
"**This should be enforced at time of submittal - we cannot require users to populate this when they open General Info.**"   

Should I ignore that sentence in the first comment?

**Comment by impittman** [comment]
@ehsan67 I will test again via submittal and see if I get an error. I will also clear my browser history in case that was an issue too.

**Comment by impittman** [comment]
@ehsan67  @leeensminger  Tested and it works, my fault for the misinterpreting. The following error was received, all is good and I think we can close this issue:
![error trapping](https://user-images.githubusercontent.com/16418393/38696230-1d04f722-3e7e-11e8-94da-f38b107b42cf.png)
