### ISSUE TITLE
Admin - Submitted Inspection Forms - Submitted Date Format

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#113]
In Recent Submitted Inspection Forms, reformat the display of the dates to a more standard format.  They should be formatted as either:
11/10/2017 or
Nov 10, 2017

![image](https://user-images.githubusercontent.com/4103847/35437325-e1b7859a-025f-11e8-9c49-0eef82718db0.png)

**Comment by impittman** [comment]
Will this mess up the filter feature for the date? If we make this 11/10/2017 for example, it goes back to the filtering problem of getting only certain records, not all dates in November. The work around was the Month in three letters first - JAN as an example.

**Comment by leeensminger** [comment]
@impittman Good point - but if we go with three letters, we need to get rid of the "/" character. 

My primary concern is that "Nov/10/2017" is not an acceptable display format for a date.

**Comment by impittman** [comment]
@leeensminger Makes sense to me, just didn't want to reinvent the problem with the 11/10/2017 example.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this appears updated, closing issue
![form submit date](https://user-images.githubusercontent.com/16418393/36224797-8a117e34-11c0-11e8-9087-64991051a675.JPG)
