### ISSUE TITLE
Admin - Submitted Inspection Forms - add action column to include the PDF inspection form

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#114]
Within the Submitted Inspections page, we need to provide a link to the final PDF version of the submitted inspection.  We should add an action column in this grid, to hold an icon that when clicked, opens the PDF inspection form.

![image](https://user-images.githubusercontent.com/4103847/35437464-7dbe2958-0260-11e8-9368-f17db0517668.png)

**Comment by kanglu666** [comment]
Add new function for export to PDF report?

**Comment by leeensminger** [comment]
@ehsan67 May just be a placeholder for now until the reporting functionality is finalized

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
the report function for download is present, will test functionality fully once we get the reports built at a later date. closing the issue.
