### ISSUE TITLE
Inspections - Weather - Weather record date formats

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#115]
Same as #113 but in the weather page.

When user is in an inspection weather details, and clicks "Load more" to see all 7 days of weather, the weather record date is in the same funky format like "Nov/10/2017".  We should drop the "/".

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
new format is added, believe this can be closed
![weather format update](https://user-images.githubusercontent.com/16418393/36224553-e6aa72d2-11bf-11e8-90af-923608b68f2c.JPG)
