### ISSUE TITLE
Reword Delete Inspection Confirmation Message

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#116]
When selecting an inspection to delete, the message below pops up to confirm the user indeed wants to delete the record.

Please change the highlighted word "delete' to "deleted"

![delete insp](https://user-images.githubusercontent.com/16418393/35630596-be316ec2-0699-11e8-997a-0ea32e3b324c.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated, closing issue
