### ISSUE TITLE
change wording in warning message for attempting to delete a previously submitted inspection

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#117]
When attempting to delete a submitted inspection, the following message appears. Please change "deleted" to "delete".

![delete insp 2](https://user-images.githubusercontent.com/16418393/35630689-f868fd3a-0699-11e8-9ee3-107578583809.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated and worked during testing, closing issue
