### ISSUE TITLE
Reset photo data value to be blank after deleting a photo

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#118]
If possible, can the fields related to a photo get reset to appear blank when a photo is deleted? In the screen shot below, I deleted the inspection photo associated to the inspection, but the values still show in the fields. It was the only photo for this inspection.

![photo delete](https://user-images.githubusercontent.com/16418393/35630927-8733581c-069a-11e8-8cc6-7e40dfa0de25.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this appeared to work when testing, closing issue
