### ISSUE TITLE
Change initial default for General Form - Non Inspection Reason

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#119]
If possible, can you have the NonInspection Reason in the General Information Form be deactivated when first creating an inspection and initially filling out the general form.
Here are the steps taken to get the replicated issue:
1) Create an Inspection
2) Go to the General Form for the first time for this new inspection.
3) The Inspection Completed is defaulted to Yes
4) The Non Inspection Reason has a default of "too wet" even though the Inspection Completed default is set to "Yes". The Non Inspection Reason should be a default to blank just like it does when you edit to a "Yes" on this form. 

![inspection reason defaults yes](https://user-images.githubusercontent.com/16418393/35638771-f516a720-06af-11e8-8837-368df98aae1a.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this updated appears to work, closing issue
