### ISSUE TITLE
Vegetative Review Form Submittal Message - Edit Comment

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#12]
The warning message for the final submittal of the Vegetative Review form needs a couple of edits:
Make the word "Sure" lower case  to "sure"
Make "U" to you.

![warning message 2](https://user-images.githubusercontent.com/16418393/32061706-5effa770-ba40-11e7-924e-9d436bbe4eec.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this issue is resolved
