### ISSUE TITLE
Filtering options in the Project List under Inspections

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#120]
I am testing out the filtering process for the Project List under the Inspections section (see below screenshots). When filtering, the option to enter multiple filter parameters does not function as one would expect. For example, if I have a projects that have a "32..." in the number, I can enter that and will see project that have "32...". However, if I want to narrow that down further by say also filtering on the Contract Number, this does not work. I am capturing this below in a screenshot too. My question is the following: Is it expected that a user should be able to search via multiple filtering parameters? Not necessarily by the parameters used as an example, but as a multiple filter, especially as the project lists gets long and likely has projects with similar associated contract numbers, NOI numbers, etc.

Process I took for replication in Admin
1: Filter task number for "32" I should see two, here which I do.

![filter 1](https://user-images.githubusercontent.com/16418393/35699774-ef75f6b6-0788-11e8-822b-097b0a703614.JPG)

2: Further filter down by Contract Number. I would expect to see one record for the project named "Br -3 587..." from the above example when I use the search of "7" for Contract Number, I don't. It is as if the last digit was filtered on for the contract number when using a multiple filter approach.

![filter 2](https://user-images.githubusercontent.com/16418393/35700003-a529edfa-0789-11e8-9932-874a6b31db30.JPG)

**Comment by leeensminger** [comment]
@ehsan67 The filtering components are functioning inconsistently across fields within each data grid.  This seems to affect most grids in the system.  Do you need an explicit list of these grids and fields that need to be modified? 

What is expected to happen - The query function, for all fields across all tables, should be returning field values that match the search characters ANYWHERE within the field values (beginning, middle, or end).
For example, in Admin/Forms, I should be able to search the "Forms" field by "Rating", and get all Inspection Rating Form values.  Or, I should be able to search "Final" and get all Semi-Final and Final form types.  
- for date fields, the search should be returning search values from anywhere within the field value, like "Apr" for all April results, "03" for day values, and "2017" for year values, and get all results where any of those are valid characters.  This is working fine.

What's currently happening - 
The inconsistency is in non-date fields, around whether the search looks for the search characters at the start of the field value, the middle, or the end.  Examples below.  
Examples on the Admin/Forms tab - 

- The "Contract  No" field searches are very inconsistent - for values in the field like "4567" and "72011073026", when user types filter value of "6", I only get "4567".  when I type "7", I only get "4567".  When user types "72011073026", I get zero results.
- The remaining non-date fields (Form, Contract Name, Inspector, and Status), all appear to be currently filtering based upon the beginning of the field value (i.e., where searching "Rating" in the "Form" field finds zero results).   These should be more wildcard based.

 **All date fields** - the searching is working appropriately, and should not be changed.  For example, Admin/Forms "Submitted Date" field is working correctly, as it should.

**Comment by impittman** [comment]
@leeensminger @ehsan67 
I noticed on testing that the Date Field in Admin-Forms is not working. I entered "F" for February inspections submitted and got the following, note March is included:
![bad filter](https://user-images.githubusercontent.com/16418393/39200322-61da6c22-47db-11e8-9645-f5f8f5deb2db.png)

**Comment by ehsan67** [comment]
kci ready

**Comment by ehsan67** [comment]
ready at kci

**Comment by impittman** [comment]
I noticed the following filters do not work on testing. The remaining filter fields appeared to be working in both the Admin and Inspections part of ES2M as specified:

Admin - Specs: These listed below do not perform a filter action when numbers or letters are entered. 
Spec Num
Description
Described Fix

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
updated and this is working, closing issue
