### ISSUE TITLE
Change wording in project team member delete confirmation message

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#121]
Please change "user" to "member" in the confirmation message for successfully deleting a project team member.

![change message](https://user-images.githubusercontent.com/16418393/35705529-92ffd994-079a-11e8-9572-225ea84801f8.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated, closing
