### ISSUE TITLE
change "user" to "member" in the warning message that occurs when a user selects delete for a project team member.

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#122]
Please change "user" to "member" in the warning message that occurs when a user selects delete for a project team member.

![change 2](https://user-images.githubusercontent.com/16418393/35705706-228d8ba6-079b-11e8-9793-a33c7914efa9.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated, closing this issue
