### ISSUE TITLE
Edit pop up message for downloading attachment in the Attachments tab found on the Operation Form under Inspections

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#123]
Edit the pop up message for downloading an attachment in the Attachments tab found on the Operation Form under Inspections. Currently, when you hover over the icon below, the pop up message states "Download Current Checklist". This is not accurate as the user is not downloading a checklist here, but a project attachment.

![update pop up](https://user-images.githubusercontent.com/16418393/35746540-0595a656-083f-11e8-8f07-9f82410601e3.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
works, closing this issue
