### ISSUE TITLE
clarify the purpose/function of the "Upload Revised Checklist" button found in Inspections - Operation Form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#124]
Steps to see where my question stems from:
-Inspection - Operations form pops up
-Go to the SWM Facilities tab
-Click Edit for SWM Facilities

Can you clarify what the "Upload Revised Checklist" button and the associated message is referring to? Is the revised checklist the file attachment I can upload in an edit session? If so, do we need this button?

![question on upload checklist](https://user-images.githubusercontent.com/16418393/35748692-cb16d51a-0846-11e8-8386-8f9e18f807ee.JPG)

If the "Upload Revised Checklist" button is to bring up a list of checklists to associate to the SWM Facility, this is not happening.

**Comment by leeensminger** [comment]
@impittman This button should support the following:
1. user goes to _File (upload only)_ and browses to and selects a revised checklist (PDF file) that is on their local
2. user clicks Upload Revised Checklist
3. system submits the file as the most recent checklist

The Upload Revised Checklist button should be disabled until a file has been selected in the _File (upload only)_.  If its not, please log a bug for Ehsan.

**Comment by impittman** [comment]
@leeensminger The button gives an error message to select a BMP first. I presume that is ok. I do need to assign this as an issue since the new checklist downloaded does not overwrite the old one. Therefore, I am unsure if it is working as described.

**Comment by impittman** [comment]
submitted new issue, closing comment
