### ISSUE TITLE
Note in Small Construction Diary Specification

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#125]
There is not an option to add a Note for specifications in the Small Construction Diary Form. The other inspections have the option to attach a note to a specification. Does this need to happen here too?
Steps:
-Small Construction Diary Inspection chosen
-Click Specification
-At the bottom in other inspection forms with specifications/deficiencies, there is a note button to associate a note to a specification. Not the case in small construction diary. However, like the other inspection forms, I can add a photo. Should the user be allowed to add a note too?

**Comment by leeensminger** [comment]
@impittman The Notes functionality is expected to be not present in the Small Construction Diary inspection.  This should include Notes, relationships to Photos or specs, etc.  

Notes should be entirely stripped from this inspection type.

**Comment by impittman** [comment]
@leeensminger Thanks, just wanted to make sure this difference in functionality was accurate. No other notes are in Construction Type. Closing issue
