### ISSUE TITLE
relationship between deficiency and photos/notes

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#126]
From my understanding, when a user sets the  Deficiency from “yes” to “no” in an inspection specification, the system will remove the Deficiency and perform a cascading delete of any notes and photos related to the Deficiency. Where is the link between photos and notes to deficiency, these only seem to only relate to the specification and not the deficiency itself?

**Comment by leeensminger** [comment]
@impittman Not needed.  Let's remove this requirement to delete downstream child entities.
