### ISSUE TITLE
Fix Warning Message for Adding a New Specification Set

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#128]
Fix Warning Message for Adding a New Specification:
The message pops ups when:
-Selecting Admin
-Selecting Specs
-Clicking the + to add a new Specification in image below
![fix2](https://user-images.githubusercontent.com/16418393/36355714-47eceeae-14df-11e8-9589-e14e5f3f548a.JPG)

-Clicking Save

**Message currently, please change "u" to "you", make "Sure" all lowercase.**
![fix](https://user-images.githubusercontent.com/16418393/36355717-542c9b10-14df-11e8-9b1b-a998c7746648.JPG)

**Comment by ehsan67** [comment]
@leeensminger KCI ready

**Comment by impittman** [comment]
Warning message is updated
