### ISSUE TITLE
Fix Message for Renaming a Specification Set

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#129]
The following message appears when attempting to rename a Specification Set. Please change "been" to "being" and "an" to "a".
![fix 3](https://user-images.githubusercontent.com/16418393/36355837-5cc86496-14e1-11e8-8f99-119f7fd37916.JPG)

Steps to get here:
-Select Admin - Specs
-Select the edit icon beside the Select a set spec” field box.
-Rename the Specification Set to the same name as a currently existing set and click save.

**Comment by ehsan67** [comment]
@leeensminger KCI ready

**Comment by impittman** [comment]
The warning message has been updated
