### ISSUE TITLE
The Final Regulatory Review Form would not submit 

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#13]
-Could not submit the final Review Form after setting the inspection to complete status. I did have 2 deficiencies in the inspections if this matter. I attempted a couple of times, and signed in and out of ES2M as well, but still received an error.

Steps used:
	-Inspections- Projects – Selected Regulator Review Form that I wanted to submit- Submittal

Error message received:
![reg form issue](https://user-images.githubusercontent.com/16418393/32062019-44baddca-ba41-11e7-995f-2999942c36f2.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this issue is resolved
