### ISSUE TITLE
Fix Warning Message for Deleting a New Specification Set

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#130]
Fix Warning Message for Deleting a New Specification Set:
Change "Sure" to "sure" and "u" to "you"
![fix4](https://user-images.githubusercontent.com/16418393/36355930-bf150086-14e2-11e8-8ef7-8419366aa898.JPG)
 The message pops ups when:
 -Selecting Admin
 -Selecting Specs
-Clicking Delete at the end of the “Select a set spec” field box.

**Comment by ehsan67** [comment]
@leeensminger KCI ready

**Comment by impittman** [comment]
Tested and it is corrected
