### ISSUE TITLE
Fix the message that appears when adding a Specification to the Specification Set in Admin

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#131]
Fix the message that appears when adding a Specification to the Specification Set:
Please remove the added info after the word "new!". It appears to maybe be a database field or something.
![fix 5](https://user-images.githubusercontent.com/16418393/36356246-2c8e5a14-14e7-11e8-9a42-9098fbd2a32a.JPG)

**Comment by ehsan67** [comment]
@leeensminger KCI ready

**Comment by impittman** [comment]
This was corrected
