### ISSUE TITLE
Inspection Submittal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/DelDOT-ES2M#133]
When the user creates an inspection form the system will successfully save the information and show the form in the operations workbench. When the user clicks the "submit" button, the system presents the following error:

![es2m_submit](https://user-images.githubusercontent.com/4129185/38200413-3f5a3860-3662-11e8-95f3-16fa83cf523a.PNG)

To recreate: select the US 301 Construction Project, then try to submit any of the already created forms. 

This is probably a data issue as the system does allow the user to submit an inspection form for BR 3-587 on SR26

**Comment by ehsan67** [comment]
@leeensminger KCI ready

**Comment by impittman** [comment]
This has been corrected, tested on both Inactive and Active Project Status and by also creating and submitting new Inspections.
