### ISSUE TITLE
Default Due Date is 0 despite being defined in Specifications Set

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#134]
Default Due Date is 0 despite being defined in Specifications Set

Steps to find this:
1) Select an Inspection Rating Form
2) Click the Specifications button at the lower part of the form
3) Click Deficiencies 
4) Make the Deficiency = Yes
5) The default date, pictured below, should be auto populated from the Specifications Set. Usually it is 21, 14 7 days, etc.
![screenshot_1](https://user-images.githubusercontent.com/16418393/38322413-d73bb23a-3829-11e8-9377-d194ab541021.png)

**Comment by ehsan67** [comment]
@leeensminger KCI ready . Current project specification data had missing DefaultDueDate because of a bug in save function. I fixed that bug but in order to test, you need to change refresh the project specs

**Comment by impittman** [comment]
Using the testing method outlined, this worked for calculating the due date.
