### ISSUE TITLE
New BMP Checklist does not save and replace old Checklist once Uploaded

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#135]
When a user edits the BMP Checklist, the old BMP Checklist is still the document that is attached to the BMP. For example, I uploaded a new pdf Checklist using the methods below, then clicked "download current checklist". The pdf that downloaded was not the pdf I uploaded to replace the BMP checklist. It was the old one, even after refreshing and logging out/back in.

Steps to see where my question stems from:
 -Click Inspections - Operations form pops up
-Select an Inspection - I used the first in list, Br 3-587....
 -Go to the SWM Facilities tab
 -Click Edit for SWM Facilities
-Select File to upload
-Click "Upload Revised Checklist"
-Click Save.
-Click the download current checklist icon (screenshot 2)

Screenshot of where this form is on the system:
![fix_checklist](https://user-images.githubusercontent.com/16418393/38372909-72de48c8-38df-11e8-9e2c-2146dc4ccec2.png)

Where to download the Revised Checklist:
![dl](https://user-images.githubusercontent.com/16418393/38372918-781b5920-38df-11e8-8f85-fc5349c50a93.png)

**Comment by impittman** [comment]
@leeensminger we are trying to resolve the BMP checklist issue for this thread. When I upload a new pdf, just a test pdf not a template or anything, I can upload it with no issue. However, I cannot download the checklist as a user. It does not appear to associate to the BMP either.  

-Is there a standard checklist template that creates the association of the checklist to the BMP and/or inspection (see Lync comments below)?
Here is my conversation with Ehsan for relevant context:
Ehsan Eslamloueyan 15:57: 
Maria, how do you create PDF documents that contain the inspection information?
I am trying to reproduce the upload checklist issue
Maria Pittman 16:00: 
for this i was only just uploading a test pdf of whatever 1 page document i could find since we don't have any checklists 
it is my understanding it should just be a direct upload of a file
Ehsan Eslamloueyan 16:02: 
it doesn't work for me , the process requires the pdf keywords (it is a meta data inside the pdf file) to carry Inspection_ID
that might be the reason you logged it as an issue
the pdf that you sent me has something in "keywords" meta data but doesn't seem to be a valid inspection ID


-From the Requirements directly below, it doesn't appear to have a specific format for the checklist and inspection ID in 8.0. However, the remaining requirements keep mentioning a template, but nothing  on a keyword for linking the checklist to an inspection that I could find:
![checklist 2](https://user-images.githubusercontent.com/16418393/38710694-37e35ba0-3eb1-11e8-9c0a-9c9d98c14cc3.png)
![checklist 3](https://user-images.githubusercontent.com/16418393/38710701-4301d624-3eb1-11e8-912d-a9ba13ebf11c.png)

**Comment by leeensminger** [comment]
@impittman  See comments in #136 .  These issues are somewhat related.

There is no naming convention required when the user updates and uploads a revised checklist.

**Comment by impittman** [comment]
@leeensminger I presume this is related to issue #136 and the work flow defined:
4.The user uploads the file (user clicks "Select File", browses to the PDF they have updated and saved locally, and selects this file), and clicks "Upload Revised Checklist".
5.The system takes the uploaded file, saves it to the system as associated to the selected BMP.
 **Note - between steps 4 and 5, the system tracks this using a key ID. BC or Lu would have more details about the technical implementation.
6.Later (the next inspection, 1-2 weeks later), the user is back in the field. The user selects the same BMP and clicks the Download Current Checklist button (again, not in UI yet). The system finds the checklist for that BMP that was most recently updated (in step 5 above), and returns this as a web download to the user.

**Comment by leeensminger** [comment]
@impittman Yes this is related, and the steps you copied above are accurate here.

**Comment by ehsan67** [comment]
@impittman kci ready
