### ISSUE TITLE
Projects List - projects list is blank/empty

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#137]
The projects list is empty but is expected to have several records.  As of this posting there appear to be 10 projects in CONTRACTS table; all 10 should be visible here.

![image](https://user-images.githubusercontent.com/4103847/38822233-c5aa0238-4170-11e8-88d4-6c5e8e179f82.png)

**Comment by leeensminger** [comment]
server error?
![image](https://user-images.githubusercontent.com/4103847/38822335-213d891c-4171-11e8-8594-38050a3ebcd5.png)

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
working now, appeared  to be server error that is resolved, closing issue
