### ISSUE TITLE
Admin - Specs - Add field to display/edit Regulatory Statement

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#139]
Within the Admin/Specs page, the system does not display a "Regulatory Statement" field.  This should be displayed, where:
Label = Regulatory Statement
Field value = MASTER_SPECIFICATIONS.REGULATORY_TEXT

Please insert this field below Spec Statement, somewhere similar to the red lines in the screenshot below.

![image](https://user-images.githubusercontent.com/4103847/38886500-2039bc74-4244-11e8-9171-93b5877b456e.png)

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
@ehsan67 The field has been added, but it is not showing up on the Web Viewer (using Chrome) or on the ipad. Is there anyway this can be corrected to fit the screen or adding a scroll bar, etc.?

For desktop, using Chrome, I have to shrink the resolution to around 75-80% to see the field and there is no option to scroll down (normal screen size 90% depicted below):
![nromal screen size](https://user-images.githubusercontent.com/16418393/39194142-8b3f3854-47cc-11e8-9673-5db2d495c8bc.png)

For the Ipad, using Google Chrome, this field is not visible and the bottom part of the form does not swipe downward like the other forms do. It is almost like that function is locked on the Admin-Spec form only. Please test/confirm this on another Ipad as the Apple I am using from KCI is not the best.
![img_0058 1](https://user-images.githubusercontent.com/16418393/39194312-f90c911a-47cc-11e8-8d9b-cf33c57afbcd.PNG)

**Comment by impittman** [comment]
works great on both the ipad and the desktop, closing issue
