### ISSUE TITLE
Unable to add new projects under Admin - Projects section

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#14]
I was unable to add "New" Projects under the Admin - Projects section of ES2M. I was logged in under the admin username and password. Lee attempted with the same login and was successful. I received a fail on each attempt with the message below:

Steps taken:
Admin - Project - New - Fill in all details - set as Active - save

![create error](https://user-images.githubusercontent.com/16418393/32063275-bd3eb372-ba44-11e7-81e3-fbffa71c3080.png)

**Comment by kanglu666** [comment]
when add new project, the location info (Latitude and longitude fields) are required in the address section.
warning message has been added. 
ready for testing in next release

**Comment by impittman** [comment]
When attempting to add a new project today, Lee and I had no success in creating a project. I imputed a lat/long as well as the actual address but this did not resolve the issue. The same error message as previously shown occurred.

**Comment by kanglu666** [comment]
working fine, please test in next release

**Comment by impittman** [comment]
working in new version
