### ISSUE TITLE
Weather date that first populates in Weather form does not update correctly

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#142]
I noticed that when I click on the Weather button for an inspection form, the initial weather shows the wrong date. I think this may be occurring because a refresh is not happening between the weather feature and the selected inspection. 

Here are the steps I used for recreating:
1) Select a project from the list -I used the highlighted one:
![selected proj](https://user-images.githubusercontent.com/16418393/39197025-13891026-47d3-11e8-8eee-aeb8f08c75c5.png)

2) Select an inspection, in this example I used the highlighted inspection, inspection date of 3/29/2018:
![select insp 2](https://user-images.githubusercontent.com/16418393/39197868-27af2a98-47d5-11e8-984b-eebc875a4862.png)

3)I clicked the weather button and it populates incorrectly for the date of 4/17/2018
![wrong date 2](https://user-images.githubusercontent.com/16418393/39198142-d5fe42e6-47d5-11e8-8043-5bb5aa932778.png)

4) Then the list is populated for the past 7 days of what appears to be the system date, not the last 7 days from the inspection date:
![wrong dates](https://user-images.githubusercontent.com/16418393/39198566-e8660148-47d6-11e8-93e4-44705beb4b6d.png)

5) I select the next inspection submitted and then I checked the General Info form for the inspection date, it is for 4/10/2018. It also has the initial weather date of 4/17/2018 when selecting the Weather button, where it should be 4/10/2018.

**Comment by ehsan67** [comment]
ready at kci

**Comment by impittman** [comment]
@ehsan67 @leeensminger 
The date being populated for the weather page is not always the correct date. Below is an example to help show where I am noticing the issue:
1) This is in the unnamed Project with the Contract # as 87654. I am using the Semi Final inspection with the date of 5/22/2018.
![gen info date](https://user-images.githubusercontent.com/16418393/40550398-7d9654d8-6029-11e8-9bbc-79db27bd1d7a.png)

2) The weather page shows 5/23/2018 when you click the Weather button, instead of 5/22/2018. It should start with 5/22/2018 to show weather for the inspection.
![wrong date pop](https://user-images.githubusercontent.com/16418393/40550453-a8dd68de-6029-11e8-9f47-2531212b7933.png)

**Comment by ehsan67** [comment]
@leeensminger @impittman  there is an explicit logic in the code that adds one day to the date and then run the query, should I remove that?

**Comment by leeensminger** [comment]
@ehsan67 Yes please remove.  That should not be there

**Comment by ehsan67** [comment]
@impittman  ready kci

**Comment by impittman** [comment]
this is working as expected
