### ISSUE TITLE
General Info - Remove Form ID field from General Info UI

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#143]
For all inspection types, within the General Info, the first field shown is the Form ID.  This is not relevant to users and should be removed from the UI.

![image](https://user-images.githubusercontent.com/4103847/39541471-d5eb6dda-4e13-11e8-837d-dc6f3de8be12.png)

**Comment by ehsan67** [comment]
@leeensminger  so we don't care what is being saved there?

**Comment by leeensminger** [comment]
@ehsan67 No, it's a system-calculated field.  I think its the primary key.  But its definitely not relevant for the users.

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
updated, closing issue
