### ISSUE TITLE
Weather Page does not always populate with data

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#144]
We have noticed on testing that the weather page does not always populate with data. Here are the scenarios when this occurs:

1) No weather is loaded for projects that have a Status of "Active". The projects with an "Inactive" Status seem to load fine.

2)There have been several days where _**no data**_ is loaded onto the weather page regardless of project status. Could this be due a failure to connect to the server for the weather service being used?

3)If the weather data is not populating due to failure to connect to the weather service, then we need to catch these instances and display text that says the DEOS service is down – instead of just a blank page.

**Comment by ehsan67** [comment]
@impittman  the reason there is no data in the table is that we are getting any data from weather service for that station and date combination.
I change the UI to show a message when the table is empty

**Comment by impittman** [comment]
The message shows up as requested when no weather is displayed.
