### ISSUE TITLE
Remove ID field from Notes UI

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#145]
For all inspection types, within the Notes, the first field shown is the ID. This is not relevant to users and should be removed from the UI. This is similar to GitHub issue #143.

![screenshot_2](https://user-images.githubusercontent.com/16418393/39867172-25d2b198-5443-11e8-88db-6b7453bec85e.png)

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
edited as noted, closing issue
