### ISSUE TITLE
Integrate PDF report to "Latest Submitted Inspection Forms" page

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#147]
On the Forms tab, the system includes a placeholder action button for downloading the report.  The reports are now mostly ready, so please work with Gerry to tie this together, so when the user clicks the Download action button, the report is generated and delivered to user.

![image](https://user-images.githubusercontent.com/4103847/40120849-303da4bc-58ee-11e8-9912-559c04ce3cef.png)

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
@ehsan67 The Inspection Report Form downloaded with no issues. However, I got the following messages for the other reports. Is this to be expected? I was unsure if these reports were not final and if this is the reason for the error.

Semi Final
![semi-final report error](https://user-images.githubusercontent.com/16418393/40398103-c65a34ec-5e25-11e8-861b-d09db5e17adf.png)

Construction Diary
![construction error](https://user-images.githubusercontent.com/16418393/40398125-dc623492-5e25-11e8-8a25-0e8e0769db4a.png)

Vegetative Review
![veg report](https://user-images.githubusercontent.com/16418393/40398127-e3aab22e-5e25-11e8-83a4-9983885bb4ca.png)

**Comment by ehsan67** [comment]
@impittman  those reports don't exist yet , that is the reason of those errors

**Comment by impittman** [comment]
@ehsan67 thanks for the clarification. I will leave this open in my assigned issues to test functionality once all reports are ready to go.

**Comment by leeensminger** [comment]
Closing for now - we'll develop these reports in the future if needed on other GH items
