### ISSUE TITLE
IRF Report - Update Specifications

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#148]
[Specs.xlsx](https://github.com/kcigeospatial/DelDOT-ES2M/files/2010063/Specs.xlsx)
@gerrykelly We reviewed the IRF report with stakeholders yesterday.  The only minor modification we need is to add a category header - one for each category set of specifications.  The attached Excel includes data sources, and a mockup design, for what this might look like.  Also included are sources for the "Y/N" fields.

Please advise if this format is feasible, and if so, please go ahead and implement.

**Comment by leeensminger** [comment]
The selection set is - for the given inspection, all INSPECTION_SPECIFICATIONS.  As noted in the doc attached above, you'll have to join this to other table(s) to get needed info.

**Comment by gerrykelly** [comment]
@leeensminger 
Done, ready for test (keep in mind the scoring table section is just a mockup, if you'd like to work on that or just let me take a shot after I do the specs and scores part)

**Comment by gerrykelly** [comment]
@leeensminger 
Ready for review.  The table based on the scoring on page one is still a mockup and needs to be reworked based on this Specifications section.  I am going to make that an issue and assign to you.

**Comment by leeensminger** [comment]
tested good
