### ISSUE TITLE
IRF Report - update 1st page header

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#149]
The existing header is correct per the mockup provided, but the change below needs to be made:

Remove line 2 and line 3
Insert "Delaware Department of Transportation" as line 2

![image](https://user-images.githubusercontent.com/4103847/40132237-3fe3201a-590a-11e8-8bc9-da3cc253ab97.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Done, ready for test

**Comment by leeensminger** [comment]
tested good
