### ISSUE TITLE
Submitted inspection form - Search Contractor

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#15]
Where is this field?  Do we have it?  Need it, if not.

**Comment by kanglu666** [comment]
Date Range search added.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by impittman** [comment]
does inspector = contractor in this update?

**Comment by leeensminger** [comment]
@impittman Inspector is different than contractor.  Contractor refers to construction contractor. 
 Contractor will come from either:
1. a field in the Contracts/Projects table
if not that, then:
2. a user role within the project team

Can you identify where this information is held, and communicate to Ehsan?

**Comment by impittman** [comment]
@leeensminger based on your explanation, I think this is working as needed. Here is my understanding and the functionality, let me know if this is inaccurate:
The search in Admin for submitted inspection forms has the option to search by contractor. We only have Mumford and Miller right now in the database, and as expected, this pops up. Not Inspector names. If this is good, we can close out the issue.

**Comment by leeensminger** [comment]
@impittman Yes that description is correct.

**Comment by impittman** [comment]
@leeensminger Thanks for confirming, closing out issue.
