### ISSUE TITLE
IRF - 1st page formatting

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#150]
There are a few items on the 1st page that do not have a line space between them, which is inconsistent.  please insert a space at the locations indicated in red:

![image](https://user-images.githubusercontent.com/4103847/40132624-507f7e4a-590b-11e8-808d-665cde34e330.png)

**Comment by gerrykelly** [comment]
@leeensminger
Done, ready for test (keep in mind the scoring table section is just a mockup, if you'd like to work on that or just let me take a shot after I do the specs and scores part)

**Comment by leeensminger** [comment]
tested good
