### ISSUE TITLE
IRF - Photos - delete "URS" label

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#151]
Delete the "URS" text in the top left corner of the Photos page.

![image](https://user-images.githubusercontent.com/4103847/40133051-87d88192-590c-11e8-9a62-5d61377979cc.png)

**Comment by gerrykelly** [comment]
@leeensminger
Done, ready for test

**Comment by leeensminger** [comment]
tested good
