### ISSUE TITLE
IRF report DEFICIENCIES clarificaction

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/DelDOT-ES2M#152]
@leeensminger 
If the content and format of the DEFICIENCIES section is basically good, then I should rename CURRENT DEFICIENCIES to just say "DEFICIENCIES" and delete that second (NO) PREVIOUS DEFICIENCIES table, correct?
However if you decide that we are going to support current vs. previous, then the data and logic would need to be clarified.

**Comment by impittman** [comment]
Following up on this comment, in running the IRF report, I noticed that the previous deficiency is reported as the same as shown for current deficiency when this is first inspection for a project with a deficiency. Here is an example to illustrate:   I created an inspection and assigned a deficiency to a specification. This was the first inspection to have a deficiency for this project. In the report, it shows like  the screenshot below, noting the previous deficiency is the same as the current deficiency. Is it possible to have the "previous deficiency" be blank when no previous deficiency is reported for the project?

![def issues](https://user-images.githubusercontent.com/16418393/50160881-49f40180-02a8-11e9-8c39-2cefd2924613.jpg)

**Comment by leeensminger** [comment]
@gerrykelly I echo @impittman comment - two things need to happen on this one:
1. Where we currently have "No previous deficiencies"... this should display "Previous Deficiencies" (for all inspections, all the time - this can be a static text value).
2a.. The "Current Deficiencies" table should show those deficiencies that are new, generated during the current inspection.  The "Previous Decriptions" table should show those deficiencies that carry over from the previous inspections.
2b. If there are no deficiencies that are carried over from the previous inspection, then the first row in the "Previous Deficiencies" table should read "None" - or something simlar, to indicate that there are no previous deficiencies.

@gerrykelly is it clear how to obtain the specific logic, to detremine whether inspections carry over from the previous inspection?  If not, then between Maria and Lu we need to figure this out to support this.

**Comment by gerrykelly** [comment]
@leeensminger @impittman 
So far as current deficiencies, I think that is working as intended/described already -- issues observied -- correct?

For Previous Deficiencies I would like to have just enough test data that will support generating the results you expect from an inspection that has 2 previous inspections (IRF ID 149 has one prior -- 147 -- so that's a good starting point) -- I assume the common identifier for inspections related to the same entity is CONTRACT_ID.  Then each of the previous inspections should have a deficiency that you expect to see in the report and one or more you don't.  If nothing ever should be shown from inspections more than one back from the current let me know so I only look back one inspection earlier than most recent.



The SQL below (which you can run if it helps) is my starting point whereby I get all deficiencies from earlier-than-specified inspection for the same contract_id.  So then my next step is to query which records to include in/exclude from the report based on the logic you provide.  (As I understand it now with the current data I would not show any of these in the report bc their [DEFICIENCY_STATEMENT]s don't match anything from the 149 inspection but let me know)

SELECT [INSP_RATING_FRM_ID],  [INSPECTION_RESULT] ,[STATION_LOCATION] ,[SPEC_CATEGORY] ,[SPEC_NUMBER] ,[DEFICIENCY_STATEMENT] ,[FIX_STATEMENT] ,[DUE_DATE] ,[INSPECTION_SPECIFICATION_ID]     
FROM [es2m].[dbo].[V_DEFICIENCIES] where 
[INSP_RATING_FRM_ID] in (select [INSPECTION_RATING_FORM_ID] from [INSPECTION_RATING_FORM] where contract_id = 
( select CONTRACT_ID from dbo.INSPECTION_RATING_FORM where [INSPECTION_RATING_FORM_ID]  = 149) and INSPECTION_DATE
< (select INSPECTION_DATE from dbo.INSPECTION_RATING_FORM where [INSPECTION_RATING_FORM_ID]  = 149 )) order by SPEC_CATEGORY, [INSP_RATING_FRM_ID]

**Comment by impittman** [comment]
@gerrykelly I have added some additional inspections with and without deficiencies to the 2 Projects in ES2M. Let me know if additional parameters/inspections may be needed to help with getting enough test data.  

For the logic, I think this makes sense and I am unaware of the need to only include the current and only the first previous inspection in the logic.

That said:
@leeensminger You wrote the following requirement and I want to ensure it is captured correctly:

3\. If there are no deficiencies that are carried over from the previous inspection, then the first row in the "Previous Deficiencies" table should read "None" - or something similar, to indicate that there are no previous deficiencies.   

To clarify, this means to me: If a specification was marked as deficient in a previous inspection but the same specification was not marked as deficient in the current inspection, then the deficiency should not be recorded in the Previous Deficiency portion of the report, correct?

**Comment by leeensminger** [comment]
@gerrykelly correct, we do not need to go back mroe than one inspection.

@impittman your understanding of the requirement is correct as you identified it above.

**Comment by impittman** [comment]
@gerrykelly please see mine and @leeensminger previous 2 comments above for guidance

**Comment by gerrykelly** [comment]
@impittman 
I think I have it functioning to the standards described in this thread -- a bit trickier than I thought.
-- For my testing I changed certain inspection dates.  The sample data you created had INSPECTION_RATING_FORMs for the same contract with identical dates.  I am assuming this is not what will happen in real data.
-- One part of the query for previous deficiencies looks for the same deficiency statement(s).  It probably does not matter querrywise,, but any typos like for "functioning" below should be corrected 
Deficiency: Cleanwater not functionging.

**Comment by impittman** [comment]
I created another inspection with today's date and made a deficiency. The previous inspection I created from 3/4 has no deficiency. This was captured correctly in the report. Only the current and last inspection was represented on the form. I believe this issue can be closed.

IRF Report
[report (19).pdf](https://github.com/kcigeospatial/DelDOT-ES2M/files/2930848/report.19.pdf)
