### ISSUE TITLE
IRF report page one scoring table needs to be specced out

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/DelDOT-ES2M#154]
@leeensminger 
The table based on the Specifications section scoring on page one is still a mockup and needs to be reworked,  
I can capture the total points and points awarded/excluded by category and overall and apply whatever math, adjustments and final rating logic you come up with, but what we have now does not translate vs. our example PDF

**Comment by leeensminger** [comment]
[IRF Report - Scoring Summary Grid.xlsx](https://github.com/kcigeospatial/DelDOT-ES2M/files/2014053/IRF.Report.-.Scoring.Summary.Grid.xlsx)

Attached file includes details.  Also found here: M:\2014\17141728.A\Reports\ES2M\Developer Support

**Comment by gerrykelly** [comment]
@leeensminger 
Ready for your review (also it would be good if ever there was realistic data for an inspection for the page 1 elements so we could verify that it comes out looking good)
