### ISSUE TITLE
Admin - Projects - remove asterisk from Lat/Long fields

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#155]
In the Address portion of new projects, Latitude and Longitude have an asterisk at the front of the field label.  Please remove the asterisk.

![image](https://user-images.githubusercontent.com/4103847/40302841-7ca29bea-5cbe-11e8-8d16-def48cf4fcee.png)

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
edited as noted, closing issue
