### ISSUE TITLE
Projects - Change "Not Issued Date" to "NOT Date"

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#156]
Within the Project Details, please change the field label for "Not Issued Date:" to "NOT Date:".  At your discretion, also change the database field to match.

![image](https://user-images.githubusercontent.com/4103847/44839511-faac9700-ac0c-11e8-8c22-ddfc619cc163.png)

**Comment by ehsan67** [comment]
@impittman @leeensminger did update save the project dates? I don't see those fields anywhere in the services code

**Comment by ehsan67** [comment]
@leeensminger @impittman  I checked the code and I don't see in any place that we save project date information!

**Comment by ehsan67** [comment]
I fixed the issue and now it saves all dates

**Comment by impittman** [comment]
updated as requested, edits and changes to the field work, closing
