### ISSUE TITLE
Update Spelling Under Admin - Specs

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#158]
The following error occurs under Admin - Specs
Update the spelling to "Construction":

![const in specs](https://user-images.githubusercontent.com/16418393/50105476-cf20dd00-01fa-11e9-9beb-d97258a1c0a5.png)

**Comment by kanglu666** [comment]
updated in dev, ready for testing

**Comment by impittman** [comment]
Tested and this is good to go, closing issue
