### ISSUE TITLE
Update filter boxes so they dynamically adjust to match the column width

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#16]
Some filter boxes appear to be a static width and do not match the associated column width.  Please look into making the filter box dynamically update to match the column width.

![image](https://user-images.githubusercontent.com/4103847/33093200-5132d42a-ceca-11e7-9a76-4e6112d0a6a7.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
This seems updated in Admin Forms, the date field is a bit long, but it does not look bad in the Admin Forms.  Can the filter lengths also be updated in the Inspection - Forms section. See below for example:

![dynamic filter](https://user-images.githubusercontent.com/16418393/34498483-c1272418-efcf-11e7-81e0-6f54000aeb44.JPG)

**Comment by kanglu666** [comment]
looks working fine on my side. please test in next release

**Comment by impittman** [comment]
this looks like it is working ok, we can reopen if that changes.
