### ISSUE TITLE
Update text formatting on inspection submittal email alert

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#163]
Within the email that is sent upon submitting an inspection, please add a space between "Inspection Rating Form" & "(Inspection ID:)".

![image](https://user-images.githubusercontent.com/4103847/53329730-b5ff7100-38ba-11e9-8b2e-47bee28e9624.png)

**Comment by kanglu666** [comment]
updated in local, will test

**Comment by kanglu666** [comment]
updated in dev, ready for testing

**Comment by impittman** [comment]
This has been updated in the DEV generated emails:
![image](https://user-images.githubusercontent.com/16418393/53639129-5aa0ec00-3bf6-11e9-83ed-5f84ee9590bf.png)
Closing the issue.
