### ISSUE TITLE
Inspections appear to show as Failed, even when 95%+ of points are achieved

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#164]
I submitted an inspection with only 3 minor deficiencies.  This should be considered a "pass", but the inspection shows as a fail.  Please check within [1) the first page of the sample IRF forms (provided by DelDOT), or 2) the requirements] to confirm what the percentages for pass/fail should be.  Then communicate to Lu for updating.

![image](https://user-images.githubusercontent.com/4103847/53329909-4047d500-38bb-11e9-84ed-04b1037f983d.png)

**Comment by impittman** [comment]
@leeensminger  please provide a link for this to confirm %:
[1) the first page of the sample IRF forms (provided by DelDOT)

**Comment by leeensminger** [comment]
@impittman M:\2014\17141728.A\Reports\ES2M\Documents\Received From DelDOT\Typical E&S Inspection Form\ES2M Calc Form_20150501 Revised_UNSECURED.xlsx

**Comment by impittman** [comment]
@leeensminger I reviewed this Excel; however, I did not see a formula for percent pass/fail. The only thing I noticed within is the math the show points awarded vs possible points. I reviewed requirements here and also did not see any percentage for pass/fail based on deficiencies. If you have any other sources, let me know:
M:\2014\17141728.A\Reports\ES2M\Requirements\Requirements and Design Delivery Package - v2

**Comment by leeensminger** [comment]
@impittman @gerrykelly please make it 50%.... > than 50% = pass, < 50% = fail.

**Comment by leeensminger** [comment]
@impittman @kanglu666 UPDATE: please use 69.99%.

Anything < 69.99% is noncompliant.  70%+ is pass.

**Comment by kanglu666** [comment]
checked the code, current percentage is 80%+ pass. updated to 70%+ pass. ready for testing in dev,

**Comment by impittman** [comment]
This logic has been updated. Tested on under and over 70% and got expected results.
