### ISSUE TITLE
Allow project team members to be entered manually (not from NPDES user table)

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#165]
Currently, when you add users to the project team, the system works as designed - you can select users that are in the system.  We need to enhance this, to allow us to enter any text into the name, company, and email fields.

For example, the end result should be as follows:
I come into the app, and click New User (or Edit).  I select the role from the dropdown.  The Name, Company, and Email fields are all editable, and all are NOT dropdowns. I can enter any text into each of these three fields.

![image](https://user-images.githubusercontent.com/4103847/53330545-c0bb0580-38bc-11e9-862e-f983ef1456c1.png)

And also update here, in Inspections: 
![image](https://user-images.githubusercontent.com/4103847/53330566-d5979900-38bc-11e9-8ce5-8aa4db279146.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev.

NOTE: database schema updated, web services updated.

**Comment by impittman** [comment]
I am able to type in and add a new team member. However, the action button to go to inspections does not work anymore. Steps taken to replicate:
1) cleared cache
2) logged in to admin account
3) went to project and added a team member and email (me Iva Pittman)  by free typing
4) team member saved
5) went to inspections selected the project and clicked the arrow that takes user to page to enter inspections. nothing happened. tried both projects.
![image](https://user-images.githubusercontent.com/16418393/53491878-75902680-3a65-11e9-99af-248b1e6d9f7e.png)

6) logged out, logged back in. step 5 is still occurring and I cannot go to the inspection page (tested this at 7:45 am 2/27/2019). Server seemed to be working ok

**Comment by kanglu666** [comment]
updated, please test

**Comment by impittman** [comment]
successfully tested the following:
-adding name in admin free text
-adding name in the inspection - project team as free text
both options worked and an email was sent to my free text entered email address. the report of the submitted inspection was not attached however, but this is already covered in a separate GH issues.
I feel comfortable closing this issue.
