### ISSUE TITLE
Date Format shows DD/MM/YYYY in Inpsection Forms - Notes

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#17]
When adding a Note to the Inspection Form, the date populates as DD/MM/YYYY instead of MM/DD/YYYY
![notes_date](https://user-images.githubusercontent.com/16418393/33331707-4f8f3918-d430-11e7-8862-36b9f20cc34a.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this issue is resolved
