### ISSUE TITLE
In Vegetative Review Form - Sample Location Photos can not be added

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#18]
I was unable to add a photo to the Sampled Location Form associated with the Vegetative Review form using the following methods:

-Vegetative Review Form - Selected Sampled Location - Selected Edit - then hit the Photo Link to upload
-Vegetative Review Form - Selected Sampled Location - Selected New - then hit the Photo Link to upload

In both examples, I was unable to upload a photo or fill out the date, file name, etc.

**Comment by kanglu666** [comment]
edit and add new photo functions work fine.
the "Photo Link" is a hyperlink to view the selected photo in full size

**Comment by impittman** [comment]
Ok this makes sense from a functional standpoint. As a user, it seemed as though I should add a photo here for the site location. Lee this is something that may need to be pointed out in a user guide or something as to where the photos should be uploaded and that this a hyper link to associate the attached photo to the location to prevent confusion.

**Comment by impittman** [comment]
this will be a training guide issue, design changes may be requested as an enhancement at a later date
