### ISSUE TITLE
Unable to Add Attachments to the Vegetative Review Form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#19]
I was unable to add attachments to the Vegetative Review Form. I used the following method:

Selected Vegetative Review Form – Chose Attachments link at bottom – Selected the New option – Filled out attributes and hit save (see example below):

![no attach](https://user-images.githubusercontent.com/16418393/33332236-b7b428d6-d431-11e7-8c2a-d530f7654a3c.png)

I received the following error screen:

![attach error](https://user-images.githubusercontent.com/16418393/33332258-d2963c34-d431-11e7-8291-c33e668707f1.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
issue resolved
