### ISSUE TITLE
Project Inspection is set to Complete = Yes, Non Inspection Reason still populates

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#2]
This issue occurs under the Inspections - Projects - General Information tab. 

When the field "Inspection Completed = Yes", the "Non Inspection Reason" field is to be inactive according to the wireframe. However, the "Non Inspection Reason" field box is still active and defaults to the first option in the drop down menu. 

![general info non inspection reason](https://user-images.githubusercontent.com/16418393/31959059-af8c8026-b8c1-11e7-8e68-b3aa660d4e70.png)

![wireframe non inspection reason](https://user-images.githubusercontent.com/16418393/31959113-d4f16f8e-b8c1-11e7-9b45-66cbbc5e910a.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
tested, this is issue is resolved
