### ISSUE TITLE
List space seems like a tiny fit and hard to read

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#20]
Under Admin - Project
The Project Team and Attachment lists seems quite short in space compared to the Project List above. If possible, it may help to increase the size of list boxes so the user can easily see a few team member or attachments listed and also find the scroll bar.

![proj team small](https://user-images.githubusercontent.com/16418393/33333210-536cf1d4-d434-11e7-854b-65c0bc049fda.png)

![attach small](https://user-images.githubusercontent.com/16418393/33333222-5afbb1e2-d434-11e7-8a8d-9c1f576d1da5.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
fixed on desktop version
