### ISSUE TITLE
Reword Warning Box in Admin - Project

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#21]
When editing and attempting to move forward in a Project under the Admin section, the message below pops up. It needs to be a bit more clear. Maybe to state something like: “You are in project team edit session, please save or cancel first before doing other actions!” 

![edit](https://user-images.githubusercontent.com/16418393/33333477-f2da9168-d434-11e7-9d70-c60cff4b6009.png)

**Comment by kanglu666** [comment]
it is set the way as you state above. please test.

**Comment by impittman** [comment]
Please change the word "do" to "doing" at the end of the phrase.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
issue resolved
