### ISSUE TITLE
Disable fields that are not being edited in all forms

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#22]
While not in edit mode, fields can still have data changed but not saved. This can be confusing as people may believe they are creating/saving edits to data since the field attribute is changeable while not in edit mode. To prevent this, the fields that are editable on the forms should be greyed out/non editable until the edit button is selected.

**Comment by kanglu666** [comment]
inspections: project team form updated
inspections: project attachment form updated
inspections: project SWM Facilities form updated
inspections: Inspection Deficiency form updated （IRF， CDF）
inspections: Inspection attachment form updated
inspections: Inspection specification Deficiency form updated （IRF， CDF）
inspections: Inspection specification Photo form updated
inspections: Vegetation Seeding form updated
inspections: Vegetation sample location form updated

admin: bmp checklist form updated
admin: project team form updated
admin: project attachment form updated
admin: project SWM Facilities form updated

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
issue resolved
