### ISSUE TITLE
Fields missing in Photo Page in the Inspection Form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#23]
Please add the following fields and link to their associated attributes in the web app interface for the Inspections Photos form:
Note Number
Specification Number
Specification Statement

Wire Frame:
![photo wire frame](https://user-images.githubusercontent.com/16418393/33340635-a1737b12-d44a-11e7-8734-b5216e3adc8d.JPG)

Current Web Interface for Photo Form under Inspections
![web photo interface](https://user-images.githubusercontent.com/16418393/33340699-d56c0f38-d44a-11e7-9e80-41d9ad9f6ce7.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
fields have been added
