### ISSUE TITLE
Change Photo Link to Open Photo

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#24]
In all Photo Form pages, please change the word "Photo Link" to "Open Photo".

![name change](https://user-images.githubusercontent.com/16418393/33341742-e4f16522-d44d-11e7-8631-f29fcf68bca9.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
issue resolved
