### ISSUE TITLE
Weather Page in Inspections does not show any data/weather observations

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#25]
The Weather Form found in the Inspection does not populate with data. Can you please share the logic behind getting the data to populate from a source, such as a weather station? Is there anything the user needs to do to access the weather station to get the weather data to populate in the web page?

In addition, according to the Wire Frame below, the Weather Form Page should populate with 1 weather record for the inspection date, plus the 7 previous weather records. Unfortunately, no weather observations are visible on this page and the user can not validate they were indeed populated in a table. Weather observations will need to be added to the web form.  

![weather](https://user-images.githubusercontent.com/16418393/33342037-ae764fb6-d44e-11e7-9ed1-60ba62d405b1.JPG)

**Comment by kanglu666** [comment]
logic: 
1: when the user select an inspection record, system will call a web service to get the nearest weather station based on the selected inspection's contract location

2: when the user click the weather page to view the weather, the system will call web service based on the Station and the inspection Date to get the weather information (one record)

3: user click the "Load More" button to load all 7 days' previous weather indormation

please test, it's working fine for me.

**Comment by impittman** [comment]
Thanks for the clarification. By using a different user name and the steps above, it works as outlined.

**Comment by impittman** [comment]
this works, tested
