### ISSUE TITLE
Change Submittal to Submit on the web forms

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#26]
For the following forms, please change the word "Submittal" to "Submit" (see example below as well).
-Inspection Rating Form
-Construction Diary Form
-Regulatory Review Form
-Vegetative Review Form
-Semi Final
-Final

![submittal form](https://user-images.githubusercontent.com/16418393/33342569-8ee906c8-d450-11e7-81f2-dc9636b8237e.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
issue is resolved
