### ISSUE TITLE
Unable to edit Existing Projects in Admin

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#27]
When attempting to edit Project Details in the Admin section, an error message was received. The steps taken to edit the Project Details tab: 
Admin – Project – Project Details – Selected an “Active Project” -  Edit button - Edit - click Save

Error Message Received when saving:
![cant add proj](https://user-images.githubusercontent.com/16418393/33343030-0258e370-d452-11e7-9112-ce54683e8958.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this is now functioning properly
