### ISSUE TITLE
Map Table of Contents- Change label names

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#28]
In the Map Table of Contents, please change the following:

Under ES2M BMPs
 -Change es2m_bmps.DBO.ES2M_BMPS  to ES2M BMPs

![map 2](https://user-images.githubusercontent.com/16418393/33343413-3459d19e-d453-11e7-9f3e-e74847fbaf1a.JPG)

Under ES2M Projects
-Change Contract_Events to Contract Events

![map 1](https://user-images.githubusercontent.com/16418393/33343383-20b99b7e-d453-11e7-80ab-d0ace36f5f6d.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
The updates requested were made. However, can you please change "BaseMap" to Base Map in the Table of Contents if possible? I am not sure if the layer name is preset or not.

![toc](https://user-images.githubusercontent.com/16418393/34499412-f924fd5a-efd3-11e7-9588-737fcd0efc18.JPG)

**Comment by leeensminger** [comment]
@ehsan67 please make the base map label change @impittman describes above

**Comment by ehsan67** [comment]
@leeensminger KCI ready

**Comment by impittman** [comment]
Updated and looks good
