### ISSUE TITLE
No results were shown in the Map's Identify Option/Results list

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#29]
When zoomed in to a feature, I selected the identify tool and clicked on the point (pictured below). No results were present in the Identify Results area either or on the screen any where I could find. Is this correct?

![id map issue](https://user-images.githubusercontent.com/16418393/33343688-3d63b5c4-d454-11e7-95c5-a33f0ad5f4fd.JPG)

**Comment by kanglu666** [comment]
not click, drag an extent to do the identify

**Comment by impittman** [comment]
we will be adding this to the training guide, not an issue at this time
