### ISSUE TITLE
The Notes Num field in the Notes form does not auto populate

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#3]
The issue occurs when attempting the following:
       - Clicking on Inspections - Projects - Notes tab and then adding a Note to the project

The Note Number is supposed to auto populate according to the wireframe comments. However, the only field Auto Populating is the ID field. The Note Num field defaults to 0, even when the user manually changes it to another number and clicks save.

![notes num not populating](https://user-images.githubusercontent.com/16418393/31959579-1811f94a-b8c3-11e7-9d28-4be1083476b3.png)
![notes wireframe](https://user-images.githubusercontent.com/16418393/31959586-1c25d61e-b8c3-11e7-98f5-842e45257331.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
tested, this is resolved
