### ISSUE TITLE
Warning Message should be added when attempting to add an existing BMP type

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#30]
Under Admin - Config

Currently, when a user tries to add a BMP type that already exists in the BMP Checklists Configuration, there is no warning to the user that the BMP exists already in the checklist. It would be helpful to have a prompt pop up when a user does attempt to add an existing BMP type to the list that suggests editing the existing BMP instead and to also prevent the add from occurring. In theory, the user should edit the existing BMP type not add a new same type BMP to the list.

For example, if a dry pond already exists in the checklist, then the user should add a new dry pond, but instead edit the existing dry pond check list files.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
warning message added, no issue
