### ISSUE TITLE
Change date format in Admin-Config to DD/MM/YYYY

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#31]
The current date format in the BMP Checklist Configuration (Admin - Config) is in MM/DD/YYYY. Please change it to DD/MM/YYYY.
![cofig date](https://user-images.githubusercontent.com/16418393/33383250-d11c13d2-d4f0-11e7-92d1-719ad3751ed4.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
issue resolved
