### ISSUE TITLE
Change checkbox to prompt in BMP Checklists Configuration

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#32]
Currently, the "Upload Revised Checklist" is a checkbox when adding or editing a new BMP to the BMP Checklists Configuration (Admin - Config). After talking with Lee, it seems a prompt asking the user if they want to upload a revised checklist instead of checkbox may be a better option. It would be ideal if this prompt only appeared when the user is in an edit session and not creating a new BMP to add to the list.

![checklist box](https://user-images.githubusercontent.com/16418393/33383557-a757060a-d4f1-11e7-90f4-d7860852655d.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
the message has been added and works
