### ISSUE TITLE
Remove drop down arrow, forms, and projects from the Inspections link

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#33]
Since the "Forms" link is inactive/removed under the Inspections link, Lee suggested that Forms, Projects and the drop down arrow should be removed. Instead the user should just have to click on Inspections and be directed to the forms page. 

![remove links](https://user-images.githubusercontent.com/16418393/33384588-6b0b9406-d4f4-11e7-9bdb-003fa4941e27.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated, no issue
