### ISSUE TITLE
Fix spelling in pop up box that appears after add/edit in Present During Inspection

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#34]
Please change "presnet" to "present" in the pop up box below. I received this message by going to Inspection Forms-Present During Inspection - Add or Edit (either option produces same message).

![fix popup](https://user-images.githubusercontent.com/16418393/33441187-11b574cc-d5c0-11e7-8b5f-e8a68093f657.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated, no issue
