### ISSUE TITLE
Is the DEFECIENT STRING box needed for Deficiencies form?

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#35]
On the form below, there is the highlighted box that will populate "Yes" or "No" depending on what the value is set for "Spec is deficient" directly above it. Can the DEFICIENTSTRING box be removed? This is on the deficiencies form in Inspections:

![deficient string](https://user-images.githubusercontent.com/16418393/33441395-91ba7c12-d5c0-11e7-92d3-83ba71ce3cfd.png)
.

**Comment by kanglu666** [comment]
DEFICIENTSTRING box has been removed, ready for testing in next release

**Comment by impittman** [comment]
issue resolved
