### ISSUE TITLE
Change pop up box when adding a new inspection

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#36]
Please change "have" to "has" in the pop up box below. This message occurs when creating a new inspection form under the project.

![inspection edit](https://user-images.githubusercontent.com/16418393/33441711-53974770-d5c1-11e7-83cf-0782c5f5cf35.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
issue resolved
