### ISSUE TITLE
Filter Option is not Working for Date Created in Notes

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#39]
Inspection – Inspection Rating Form- Notes- Date Created Filter
Does not work when I begin to filter on the month. I have notes that are 01/02/2018. When I search 01, nothing populates. However, when I filter 2018, the 2 notes appear. I think it is looking for year not month in the filter maybe. Please see photo examples below:

Location where I am filtering (Notes form)
![date filter 1](https://user-images.githubusercontent.com/16418393/34500566-50605c72-efd9-11e7-8e21-1a65c2b6f57d.png)

Filter attempt results using 01 for the month of January. I should have 2 not all 3:
![date filter 2](https://user-images.githubusercontent.com/16418393/34500592-6af4a67e-efd9-11e7-8107-ef4fe000f9fd.png)

Worked using 2018, but this will give all 2018 notes, not a specific date once more notes are added. This is just an example:
![date filter 3](https://user-images.githubusercontent.com/16418393/34500606-7722ce4e-efd9-11e7-86d2-1eb2e5dabdd0.png)

**Comment by kanglu666** [comment]
all date columns have been updated to “Jan/04/2018” format, and the filter works fine. also the sort works correct.
all columns filter width has been set to width: 100%.

**Comment by impittman** [comment]
the change in format resolved the filter issue, works well, closing out issue
