### ISSUE TITLE
Date Closed on Project Notes Web Form gives a date of NaN/NaN/0NaN when the Status field is “Active”

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#4]
When editing Inspection Project Notes, the Notes web Form gives a date of NaN/NaN/0NaN when the Status field is “Active”.  This date format does not allow edits to save. The following steps was used when the error was noticed:

- Clicked on Inspections - Projects - Notes tab - Edit - Set Status Active - Save. 
-It is likely that since the "Date Closed" field is default populated with NaN/NaN/0NaN, the Edit Save fails and gives me the following message:

![date issue](https://user-images.githubusercontent.com/16418393/31959978-4f3b52c6-b8c4-11e7-8bbe-fc92b71be549.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
tested, this issue is resloved
