### ISSUE TITLE
Dates are NaN in the calendar under Notes when editing an Active Note to Closed

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#40]
Under Inspection Rating Form – Specification – Notes and also in Regulatory Review Form-Notes
After selecting a Specification in the list, clicking ‘Notes”, “Edit”, then selecting an active note, changing status to “Closed” the drop down calendar is NaN. This only happens when editing an “Active” note to a “Closed” note. In addition, the Date Closed for an active note is NaN/NaN/0NaN. Is this correct?

![nan date](https://user-images.githubusercontent.com/16418393/34500703-dc0be548-efd9-11e7-8b1b-0977719a19af.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this is updated in testing, closing issue
