### ISSUE TITLE
Admin - Form Filters are not working

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#43]
The filters in Admin-Forms are not working. I was unable to get records for any of the filters using multiple attempts. 
Example: Searched for “Pass” using the Status filter. I should see one record, but I see all records.

![filter](https://user-images.githubusercontent.com/16418393/34521686-05f9ecfa-f05d-11e7-8a49-401d66288709.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this is working, closing issue
