### ISSUE TITLE
Date Filter in Inspection Form is not finding records by the month, only the numeric day

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#44]
Submitted Date Filter in Inspection Forms does not fully work. When entering 10 to get October records, I am only able to see inspections from November. I think the date filter is grabbing the actual day and not the month. I further tested by adding 09 to the filter and got no results for September. However, when using 14, I saw September records occurring on 9/14. The filter should look for month first, then day, so the user can find records from a given month.

![date filter month doesnt work](https://user-images.githubusercontent.com/16418393/34521750-6bdbea50-f05d-11e7-96e8-f5b26ff97e94.png)

**Comment by kanglu666** [comment]
date format has been updated to "Nov/01/2017". filter should be work.

**Comment by impittman** [comment]
this new format resolved the filter issue, closing out
