### ISSUE TITLE
Update Message Received in Admin

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#45]
When completing these tasks:
Admin – Project – Specification - Delete Specification
Admin – Project – Project Team - Delete Team Member
Admin – Project – Attachments - Delete Attachment
Admin – Config - Delete BMP

Please update warning message. Make “Sure” lower case and change “u” to “you”.
![u to you](https://user-images.githubusercontent.com/16418393/34522291-e6a60ec6-f05f-11e7-8660-73de9b33bf30.png)

**Comment by kanglu666** [comment]
will be ready for testing in next release

**Comment by impittman** [comment]
updated, closing issue
