### ISSUE TITLE
Admin- Project List Status Filter does not distinguish between active and inactive

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#46]
In Admin - Project
For the Status Filter, when typing “Active” it also captures “Inactive”. Is there a way for this filter to only capture “Active” I think there is only 2 status, active and inactive for status type.

![status](https://user-images.githubusercontent.com/16418393/34522398-68bdfefa-f060-11e7-8750-398fb2c62392.png)

**Comment by kanglu666** [comment]
updated, rewrite the filter module. ready for testing in next release

**Comment by impittman** [comment]
this works, closing issue
