### ISSUE TITLE
Edit Message - Add New Team Member

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#47]
Admin – Project – Project Team – New Team Member
When adding a new team member, the following message appears. If it is possible, can you please remove the Proejct_Team_ID:13 at the end of this message.

![teammember](https://user-images.githubusercontent.com/16418393/34525270-55b5ced0-f06c-11e7-8bdf-0193288ff05e.png)

**Comment by kanglu666** [comment]
ready for testing in next release

**Comment by impittman** [comment]
updated, closing issue
