### ISSUE TITLE
When an Inspection Note Status = Closed, the date closed does not default to the System Date 

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#5]
When an Inspection Note Status = Closed, the date closed does not default to the System Date as stated in the wire frame. Instead, the date is  defaulted to NaN/NaN/0NaN. 

-Steps taken to get this issue:
 -Inspections - Projects - Notes - Selected a Note Created - Clicked Edit - Changed Status  to "Closed"- Saved

This is what the default Date Closed field looked like, once Saved:
![date closed issue](https://user-images.githubusercontent.com/16418393/31960352-862c81c8-b8c5-11e7-8871-95d9c9cfdb58.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this issues is resolved under the inspection rating form - notes section
