### ISSUE TITLE
Edit final delete message for  Admin - Attachment - Delete Attachment

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#52]
Admin – Project – Attachments - Delete Attachment
Is there a way to delete the (:50) in the final message after confirming the deletion of the attachment?

![attach edit](https://user-images.githubusercontent.com/16418393/34526130-753b289c-f06f-11e7-9fe0-0ef3f0d245b6.png)

**Comment by kanglu666** [comment]
yes, i can update the message

**Comment by impittman** [comment]
updated, closing issue
