### ISSUE TITLE
Prompt user to enter value for Non Inspection Reason for the Inspection Rating Form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#56]
Inspection Form – General Information
When an Inspection Completed = No, then the user should be forced to enter a value in the Non Inspection Reason. This should only happen when Inspection Completed = No. Possibly create a prompt when the Non Inspection Reason is not populated and the Inspection Completed = No and the user clicks “Save”. We still want the NonInspection Reason to be not populated/greyed out for when Inspection Completed = Yes.

**Comment by kanglu666** [comment]
working on  it

**Comment by impittman** [comment]
This works in latest version, closing out issue.
