### ISSUE TITLE
Edit Updated Note Message for non IRF forms

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#63]
Regulatory Review Form – Notes – Adding or Updating a note
When Adding a Note in the Regulatory Review Form, the following message pops up. Since this is not an IRF form, please change the IRF to “Regulatory Review Form”. Alternatively, maybe you could just state “Selected Note has been updated!” to keep it short and limit edits. 
Also, this message occurs when adding or updating notes in the following:
Semi-Final – Notes - Adding or Updating a note – Please change IRF to Semi Final or “Selected Note has been updated!”
Final – Notes - Adding or Updating a note – Please change IRF to Final or “Selected Note has been updated!”

![update note](https://user-images.githubusercontent.com/16418393/34551097-51851bf2-f10e-11e7-9a77-cc64234a1953.png)

**Comment by impittman** [comment]
Please see initial comments, the "IRF" part needs to change for notes that are not part of the IRF inspection type, like the regulatory review for example.

**Comment by kanglu666** [comment]
all note forms message have been updated to "Selected Note has been updated!"

**Comment by impittman** [comment]
updated, closing
