### ISSUE TITLE
Add Inspection Completed to General Form for Small Construction Diary Inspection 

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#64]
Small Construction Diary Inspection - General Form: 
Add in a field for “Inspection Completed” on the General form. If Inspection Completed = No, logic should be added to match the requirements below.

![req 35 4](https://user-images.githubusercontent.com/16418393/34551130-9bfa09e0-f10e-11e7-90ab-72c8e3547da8.png)

**Comment by kanglu666** [comment]
the construction diary inspections table has no  "inspection completed" field in current database.

**Comment by kanglu666** [comment]
Inspection Completed  field has been added in to construction diary inspection table in database.
need to build the logic;
logic built in the UI, ready for testing in next relesae

**Comment by impittman** [comment]
Thanks, closing this out as complete
