### ISSUE TITLE
Weather option does not work for Regulatory Review or Vegetative Review Forms

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#65]
When inputting an inspection record for either the Regulatory Review or Vegetative Review Forms, I am unable to view the weather. The page is blank and the option to load more does not work. I have tried entering the inspections as a rain event or not a rain event and received the same result. The weather form does populate on the IFR, Semi-Final, Final, and Small project Construction Diary.

**Comment by kanglu666** [comment]
after test, looks it works fine, please test.

**Comment by impittman** [comment]
This is working in the latest version, closing out.
