### ISSUE TITLE
Small area for viewing SWM Facilities in Admin – Projects on Tablet-Chrome

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#67]
Tablet – Ipad  and Droid Format Issue, Chrome
SWM Facilities in Admin – Projects. 
In landscape format, the BMP numbers are hard to see. Is there a way that the other sections either above (Project List) or below (BMP Status) could be smaller to help show the SMW Facility to the user Vertically, the data is visible? It is our outstanding that landscape is the preferred viewing option.
![img_0006](https://user-images.githubusercontent.com/16418393/34564793-144f3528-f150-11e7-8b11-32a1c23a82bc.PNG)

**Comment by kanglu666** [comment]
layout update.

**Comment by impittman** [comment]
updates look good, closing issue
