### ISSUE TITLE
Attachments are not visible in Landscape using Tablet in Chrome

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#68]
Ipad or Droid in Chrome
Attachments in Admin – Projects. In landscape format, the attachments are not visible. You have to swap to vertical to see them. 

![img_0007](https://user-images.githubusercontent.com/16418393/34564856-7b99af42-f150-11e7-997c-be66c9d960b2.PNG)

**Comment by kanglu666** [comment]
test with scroll

**Comment by impittman** [comment]
In the tablet I am using, ipad from kci, there is no option to scroll and reducing the area by using fingers to minimize/maximize the area does not work. I have collapsed the map and the left side bar as well. No scroll bar is present in the middle section for attachments.

**Comment by impittman** [comment]
This looks great and works well.
