### ISSUE TITLE
Edit, Add, Delete Team Members is not visible on tablet for Inspections – Project Team

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#69]
Ipad or Droid- chrome
Inspections – Project Team. The bottom options to Edit, Add, or Delete Team Members is not visible in landscape. This makes editing, adding difficult without going to portrait mode. 
![img_0008](https://user-images.githubusercontent.com/16418393/34564945-c40dd4ba-f150-11e7-915f-507dc27ac51d.PNG)

**Comment by kanglu666** [comment]
test with scroll

**Comment by impittman** [comment]
In the tablet I am using, ipad from kci and a personal droid, there is no option to scroll like a bar and reducing the area by using fingers to minimize/maximize the area does not work. You can manually scroll down, if the role is showing. I have collapsed the map and the left side bar as well. This primarily happens when multiple members are loaded in for clarification, resulting in the section of role to be very minimal and not easy to see with by the user. It is not obvious that the bottom portion of this form, beginning with "role" should be manually scrolled down to see more than one option. Pleas add a scroll bar for the section beginning with "role".

**Comment by impittman** [comment]
In the meeting on 1/15/2018, it was suggested to change the layout of the form to resolve the issue. Lu is going to test a couple options to see what may work best.

**Comment by kanglu666** [comment]
layout updated, ready for testing in dev

**Comment by impittman** [comment]
this is resolved and works well, closing issue
