### ISSUE TITLE
Spelling correction in Warning Message

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#7]
If a user is in “Edit” Mode, another page cannot be activated and a warning message appears to alert the user that a save or cancel must occur before moving forward.  The following warning pops up. It may help to change the wording a bit from do to doing, if space allows.

![warning message](https://user-images.githubusercontent.com/16418393/32060019-a98c35e2-ba3b-11e7-8b4c-2a0ad0d964f1.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this process has changed for inspections with the lockout for the user to navigate anywhere else without saving/canceling edit, therefore this is closed
