### ISSUE TITLE
Options to Edit Attachments in Inspection-Attachments are not visible in tablet

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#70]
Ipad/Droid in Chrome
Inspection – Attachments
The bottom options to Edit, Add, or Delete Attachment is not visible in landscape. This makes editing, adding difficult without going to portrait mode.

![img_0009](https://user-images.githubusercontent.com/16418393/34565037-3d39c0ba-f151-11e7-9de6-268ef4c337fc.PNG)

**Comment by kanglu666** [comment]
test with scroll in tablets

**Comment by impittman** [comment]
In the tablet I am using, ipad from kci and a personal droid, there is no option to scroll like a bar and reducing the area by using fingers to minimize/maximize the area does not work. I have collapsed the map and the left side bar as well. This primarily happens when multiple attachment are loaded in for clarification, resulting in the section beginning with attachment to be very minimal and not easy to see by the user. It is not obvious that the bottom portion of this form, beginning with "attachment" should be manually scrolled down to see more than one option. Please add a scroll bar for the section beginning with "attachment"

**Comment by impittman** [comment]
In the meeting on 1/15/2018, it was suggested to change the layout of the form to resolve the issue. Lu is going to test a couple options to see what may work best.

**Comment by kanglu666** [comment]
layout updated, ready for testing in dev

**Comment by impittman** [comment]
this format is updated and looks good, closing issue
