### ISSUE TITLE
Options to Edit BMP Status or Add Files is not visible in landscape in Inspection – SWM Facilities 

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#71]
Ipad or Droid in Chrome
Inspection – SWM Facilities 
The bottom options to Edit BMP Status or Add Files is not visible in landscape. This makes editing, adding difficult without going to portrait mode.

![img_0010](https://user-images.githubusercontent.com/16418393/34565168-a801c29e-f151-11e7-86c5-263464aa6e4c.PNG)

**Comment by kanglu666** [comment]
i believe you can scroll the page up and down in tablets using finger.
please test.

**Comment by impittman** [comment]
In the tablet I am using, ipad from kci and a personal droid, there is no option to scroll like a bar and reducing the area by using fingers to minimize/maximize the area does not work. I have collapsed the map and the left side bar as well. It is not obvious that the bottom portion of this form, beginning with "BMP Status" should be manually scrolled down to see more than one option. Pleas add a scroll bar for the section beginning with "BMP Status" or reduce the white space on the middle portion of the form to make more options visible where "BMP Status" begins.

**Comment by impittman** [comment]
In the meeting on 1/15/2018, it was suggested to change the layout of the form to resolve the issue. Lu is going to test a couple options to see what may work best.

**Comment by kanglu666** [comment]
layout updated, ready for testing in dev

**Comment by impittman** [comment]
this is updated and looks good, closing issue
