### ISSUE TITLE
Last Inspection Date does not automoatically populate on the General Form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#72]
The requirements state that the Last Inspection Date should populate automatically. This does not happen on the general form as intended. 

Current General Form- Last Inspection Date shows blank, user has to add last inspection date manually.
![last_ispect_date](https://user-images.githubusercontent.com/16418393/34615199-f082e752-f22b-11e7-83b3-f1e7bb279817.JPG)

Requirement for Reference
![req 12 1](https://user-images.githubusercontent.com/16418393/34615231-12b401da-f22c-11e7-803f-730e7d742635.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
The last inspection date does auto populate. However, the date is set to the day of the inspection created, not the last inspection date prior the new inspection. 
For example, I created an IRF today (1/31/2018) and the last inspection date is also today (1/31/2018). The last inspection date should be for the last time an inspection was entered, see below.

![inspection final date](https://user-images.githubusercontent.com/16418393/35636825-4c70c984-06aa-11e8-81da-01666c43d534.JPG)

**Comment by ehsan67** [comment]
@impittman @leeensminger  is it the last inspection date for the current selected project, or for last inspection date for all projects?

**Comment by leeensminger** [comment]
@ehsan67 the last inspection date for the current selected project

**Comment by ehsan67** [comment]
ready KCI

**Comment by impittman** [comment]
@ehsan67 I think the date fields are populating in reverse order. I created the inspection below this morning. If you notice, the Last Inspection Date is today 4/12/2018 and the Inspection Date is for 2/21/2018. The Inspection Date should be today and the last inspection date for 2/21/2018.
![inspect date error](https://user-images.githubusercontent.com/16418393/38674873-83dcf6f4-3e45-11e8-89d4-b0b3b00f6c37.png)

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
@ehsan67 The inspection date field is working correctly now. However, the last inspection field is not populating correctly. The last inspection field depicted below should have the date of 3/29/2018 for this project:
Using the admin login:
-Selected Project #T23678 as this only had one inspection in the project to begin with
-I added 1 inspection today and the following data populated in the General Info form. Note the  last inspection date is today, not 3/29/2018 (the date of the only other inspection for this project).

![insp](https://user-images.githubusercontent.com/16418393/38751066-74779302-3f46-11e8-94cb-bd9822bd8d6e.png)

**Comment by ehsan67** [comment]
ready kci

**Comment by impittman** [comment]
works as expected on testing, closing issues
