### ISSUE TITLE
When a Deficiency is set from Yes to No on an non-submitted form, associated child records need to be deleted

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#73]
Please see the requirement below and an example of what should happen when the Deficiency is updated from Yes to No for an non submitted inspection form. This currently is not working as defined:

Req 14.3
![req 14 3](https://user-images.githubusercontent.com/16418393/34615682-ab3181a2-f22d-11e7-992a-959e3a993dd1.png)

Here is a sample use case to which req. 14.3 is speaking:  An inspector finds a deficiency, and marks it as such in the form.  There may be associated photos, etc.  The contractor may then fix the issue on the spot or later that same day – prior to the inspector submitting the form.  When this happens, the inspector changes the ‘grade’ on the spec so its no longer a deficiency – and the system needs to delete all child objects related to that deficiency, so it then appears that the deficiency was never even there.

**Comment by leeensminger** [comment]
@impittman The required workflow that you've laid out is correct - that is the correct workflow and a valid use case.  Please specify for Ehsan what part is not functioning and what is currently happening.

**Comment by impittman** [comment]
@ehsan67 Please review the entire thread here. Specifically, the issue occurs when the following steps are completed. The trouble occurs after you change a Deficiency from Yes to No. I outlined how to first make a Specification deficient, then how to change the same Specification to not deficient (where the deletes of deficient specification specific photos and notes should occur):

To make a Specification Deficient and add photos/notes do the following:
-Select an Inspection Rating Form
-Click on Specification button
-Select a Specification from the list
-Click on Deficiency
-Click Edit - Change Spec is Deficient drop down Box to Yes, populate other fields where needed here, hit save
-This takes you back to the Specifications page. Keep the same Specification you just made deficient highlighted/selected. Add a Photo using the Photo button, do the same for Notes. This creates Specification notes and photos for the chosen Specification (the one that we just made deficient using the steps above). 

Change Specification to Deficient = No, this should trigger a cascading delete of the Note and Photo you created above for the Deficient Specification:
-Select the same Specification from the Specification list that you made deficient
-Click on the deficiency button
-Change Spec is Deficient to NO
-Hit save
-This is where the system in theory should delete the associated photos to this Specification since it is no longer deficient. I do not think there is a link to define the Specification Photo and Notes to the Deficiency since the delete is not occurring. 

@leeensminger I presume it is also possible to have notes and photos to Non Deficient Specifications? Is this accurate? If so, does a distinction need to be made for deficient vs non-deficient Specifications photos/notes. If not, non-issue, wanting to cover all bases.

**Comment by ehsan67** [comment]
@impittman @leeensminger  The notes and photos can be added before the specification is converted to Deficient. In that case, there is no way to know if the notes and photos are captured before the specification is changed to Deficient.

**Comment by impittman** [comment]
Per an email today (4/16/2018) from @leeensminger:
I think this requirement is likely a holdover from a period of time during which the deficiencies were explicitly carried in a different table.

This requirement can be removed.  When a user flips a spec from Deficient = True to Deficient = False, the system’s only reaction should be to clear the deficiency due date field.  The system should not delete photos or notes.  

Closing issue based on this.
