### ISSUE TITLE
Add option to delete non submitted inspection form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#74]
-Requirement 12.9 states that the system will allow a user to delete the Inspection Form, if not submitted. However, there is no option to delete a form. We need to have a delete option for inspections that are not submitted. 

Requirement for Reference
![12 9](https://user-images.githubusercontent.com/16418393/34616233-81e9974c-f22f-11e7-8bae-4c4866ed2141.JPG)

**Comment by kanglu666** [comment]
delete non-submitted inspection form function has been added, ready for testing in next release

**Comment by impittman** [comment]
the delete option works for non submitted inspections, tested two different types out. Also, will not let me delete submitted inspections as to be expected. I believe this issue is resolved.
