### ISSUE TITLE
Photo Form for Vegetative Review Form-Change the word Location to Station. 

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#76]
Change the word Location to Station on the form below.

![vegetative photo form fix](https://user-images.githubusercontent.com/16418393/34617805-7cd2c1e8-f234-11e7-8540-fd2ee05a3706.JPG)

**Comment by impittman** [comment]
Should photo show location or station? On the report Gerry is creating, it definitely shows Location. I have seen both station and location in our requirements.

**Comment by leeensminger** [comment]
@impittman I think Location is preferred, as it is more general.  Also it appears that the UI (based on your screenshot) and Gerry both already have "Location" in place.  So let's go with that.

**Comment by impittman** [comment]
@leeensminger Thanks for confirming, closing out issue.
