### ISSUE TITLE
Change Description to Comments (free text field) on the Sample Location form for the Vegetative Review Form.

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#77]
Change Description to Comments (free text field) on the Sample Location form for the Vegetative Review Form.

![description to comment](https://user-images.githubusercontent.com/16418393/34618037-68d24ce4-f235-11e7-9db2-ae4c19c23e74.JPG)

**Comment by impittman** [comment]
@leeensminger Should this stay description? I believe we settled on yes, but before closing, I wanted to make sure this was accurate from any requirements updates.

**Comment by leeensminger** [comment]
@impittman Yes should be Comments.  This from Req ID 23.0 and also the original form:
 
![image](https://user-images.githubusercontent.com/4103847/38552683-eaa30890-3c8a-11e8-9c3c-ac116ac656f4.png)

**Comment by ehsan67** [comment]
ready  KCI

**Comment by impittman** [comment]
updated, closing issue
