### ISSUE TITLE
Add a Comments to the Photos form associated with the Regulatory Review Form.

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#78]
Add a Comments (free text field) to the Photos form for the Regulatory Review Form.
![reg photo issue](https://user-images.githubusercontent.com/16418393/34618391-88a2b918-f236-11e7-8e8f-f2e1151fe5d7.JPG)

**Comment by impittman** [comment]
@leeensminger Should photo show comment or description?  I have seen both in our requirements.

**Comment by leeensminger** [comment]
@impittman For all inspection photos, the term should be "Description"

**Comment by impittman** [comment]
@leeensminger Thanks, closing this one out so it won't be changed.
