### ISSUE TITLE
Date Field Format

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#8]
On the Inspection Forms, the Date Format in the "Submitted Date" field is DD/MM/YYYY. Is this correct? See example below:
![date issue 2](https://user-images.githubusercontent.com/16418393/32060324-6a73164a-ba3c-11e7-97e7-a61a8c304854.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this issue is resolved
