### ISSUE TITLE
Warning message and preventing user from editing another record while in edit mode does not work

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#82]
In testing, I was able to select a record to edit, make a change, but not save it, then go to another form edit, not save, etc. without getting a message that I am currently in edit mode as expected. In the meeting on 1/15/2018, it was suggested that when a user is in edit mode the following occurs:
-Lock the grid and the left panel to not allow a user to navigate out of the edit session.
-Hide the new and delete button from the form when in edit session.
This should happen for all edit sessions in ES2M.

**Comment by kanglu666** [comment]
logic updated in all inspection forms, ready for testing in next release

**Comment by impittman** [comment]
The new fix is great and works on every test I ran, closing this out.
