### ISSUE TITLE
Please explain the logic behind populating the Note Number on the Photo Form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#83]
When creating a note in the inspection or for a deficiency, an auto-generated note number is created. However, a deficiency with a note and photo does not show the Note Number on the form below. Where does the note number come from on the Photo Form below and does it relate to the note number for a deficiency with a photo? 

![note number](https://user-images.githubusercontent.com/16418393/34623074-a45f4782-f247-11e7-848e-165a4f052f75.JPG)

**Comment by kanglu666** [comment]
when the photo is related to the IRF inspection and also related to a IRF_NOTE, the note number will be populated in the form above.

**Comment by impittman** [comment]
Thanks for the explanation. Is there a way to add a photo to the Notes in the Specification section. For example, in the IFR, I selected the following:
Specifications - Selected a Specification - Notes - then added a note to the form below. However, there is no option to add a photo here to this note. 
![img_0014 1](https://user-images.githubusercontent.com/16418393/34752080-1a17f646-f5a8-11e7-87a2-1f11642097b8.PNG)

**Comment by impittman** [comment]
closed, related to another issue in discussion
