### ISSUE TITLE
Update the Inspector time in/out on the General Information form  

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#84]
Inspector time in/out on the General Information:  
When Inspection Type = Inspection Rating Form and Inspection Reason = Follow Up, then inspector time in and time out are required.  Otherwise, they are optional. 
Also, if the  user tries to save a General Information form with null or empty time in/out, the system should provide a notification message, indicating that the time in/out is required.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
This works in the newest version, closing out.
