### ISSUE TITLE
Remove Drop Downs for Time in/Time Out from the General Info Form

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#86]
Remove Drop Downs for Time in/Time Out from the General Info Form. This should be a free form text for the user in order to get the precise time.

**Comment by kanglu666** [comment]
the Time in/Time Out fields are free text fields with drop down options. please test
when users type in the time, make sure they have the right format:  00:00:00

**Comment by impittman** [comment]
After talking with Lee today, these two fields need to be alphanumeric text fields. Please change the field to a text field instead.  This will ensure time is being entered correctly and more user friendly by the inspector.

**Comment by kanglu666** [comment]
these two fields have "Time" type in database, it must be timefield in the UI. 
when users type in the time, make sure they have the right format: 00:00:00

**Comment by impittman** [comment]
This works using your format of 00:00:00. Training guide will address this in detail.
