### ISSUE TITLE
Hide the Reports option under the Admin tab

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#87]
Please hide or remove the "Reports" link that is under Admin. This will be a feature that may be added in at later date. For now, it needs to be removed.
![remove report](https://user-images.githubusercontent.com/16418393/34753012-91c85b18-f5ad-11e7-8720-6d06e90255b5.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
updated, closing issue
