### ISSUE TITLE
Change the General form label to "General Information"

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#88]
Change the General form label to "General Information"

![general](https://user-images.githubusercontent.com/16418393/34919519-5c5d46d8-f95d-11e7-9d6e-63149ce6d9b3.JPG)

**Comment by kanglu666** [comment]
label has been changed to "General Info", Text "General Information"  does hard to fit the layout.

**Comment by impittman** [comment]
changes look good, closing issue
