### ISSUE TITLE
Update Spelling on the Deficiencies Page

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#9]
When adding a deficiency to a specification, the box below is brought up. The following spelling edits should be made:
Change Defalut to Default
Change Datte to Date 

Steps used to get to this form:
Inspection - Projects - Select a Project from list - Chose Specifications Option - Select Specification - Select Deficiency 

![spelling changes 2](https://user-images.githubusercontent.com/16418393/32060669-781b0ed2-ba3d-11e7-9d4d-1431a5597b80.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
this issue is resolved
