### ISSUE TITLE
Change the way a New Inspection is Created 

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#90]
After discussing more of the requirements in the meeting on 1/15/2018, we need to alter the form for entering a New Inspection to show the business requirements more accurately. This is an outline of how the changes should look:
-Hide all fields but inspection type.
-Keep all types currently in the inspection type listed below.
Construction Diary Form
Final
Inspection Rating Form
Regulatory Review Form
Semi-Final 
Vegetation Review Form

Form for reference:
![new inspection](https://user-images.githubusercontent.com/16418393/34957220-9b715a04-fa24-11e7-8f53-ae5a483f26e4.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by impittman** [comment]
This is updated, see issue #100 for further comments on the drop downs, ok to close this issue for now.
