### ISSUE TITLE
In Vegetative Review –General Form, change Status to Inspection Reason and add Last Inspection Date

### ISSUE THREAD

**Issue by impittman** [kcigeospatial/DelDOT-ES2M#93]
In Vegetative Review –General Form, change Status to Inspection Reason and add Last Inspection Date

![veg insp change](https://user-images.githubusercontent.com/16418393/34920538-527fd90a-f96c-11e7-8598-b1a187fe148e.png)

**Comment by kanglu666** [comment]
there are no "Inspection Reason and "Last Inspection Date"  fields in [VEGETATION_EVALUATION] table

the status value is coming from "VEG_EVAL_STATUS_ID" field.

**Comment by impittman** [comment]
The label circled on the form needs to be changed to reflect either "Evaluation Status" or "Inspection Reason". 

I am confirming with Lee if we need to definitely add the "Last Inspection Date". If the case, we will have to add the field to the database.

**Comment by impittman** [comment]
@leeensminger  Please see comments above and see if we need to add these fields or if it was a change in requirements.

**Comment by kanglu666** [comment]
label "Status" has been updated to "Inspection Reason"

**Comment by impittman** [comment]
updated based on meeting comments and changes in web viewer, closing issue
