### ISSUE TITLE
Change ES2M Web Viewer icon at root level

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#94]
Change this icon:

![image](https://user-images.githubusercontent.com/4103847/34921196-da50e894-f94c-11e7-8a3b-663661aed71f.png)

To use this:
http://fontawesome.io/icon/book/
![image](https://user-images.githubusercontent.com/4103847/34922067-cb611186-f958-11e7-9594-d22e77c8839a.png)

**Comment by impittman** [comment]
updated and looks good
