### ISSUE TITLE
Insert regulatory text functionality

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/DelDOT-ES2M#95]
Within inspections, for a given specification - when the user clicks the "Regulatory" button, the system should display a new card, and display the regulatory text.  Regulatory text has just been updated within the following Excel:
M:\2014\17141728.A\Reports\ES2M\Design\Data_Model\Data_Seed\SampleData_v1.1.xlsx
tab = **MASTER_SPECIFICATIONS**

![image](https://user-images.githubusercontent.com/4103847/34947055-f0ad6ede-f9d6-11e7-9130-36603bbc487f.png)

**Comment by kanglu666** [comment]
"Regulatory" field has been added in MASTER_SPECIFICATIONS table for current database and data populated for this field.
web service updated, UI and function updated.
ready for testing in next release

**Comment by impittman** [comment]
This is updated and matches the source data.
